ajax/workinprogress.html
teams/index.html
teams/svatic-ictaas/index.html

Pages to review:
https://shawnthompson.github.io/bati-itao.github.io/teams/
https://shawnthompson.github.io/bati-itao.github.io/teams/svatic-ictaas/index.html

add notes as includes on the teams pages

---

index.html
learning/_template-en.html
learning/coaching/accessibility-en.html
learning/coaching/feedback-en.html
learning/coaching/index.html
learning/coaching/session-references-en.html
learning/curriculum/desktop-application-developer-en.html
learning/curriculum/desktop-application-tester-en.html
learning/curriculum/general-accessibility-en.html
learning/curriculum/index.html
learning/curriculum/web-application-developer-en.html
learning/curriculum/web-application-tester-en.html
learning/curriculum/writers-editors-translators-en.html
learning/index.html
learning/offline/index.html
projects/_template-en.html
projects/index.html
resources/accessible-documents-en.html
resources/accessible-software-en.html
resources/index.html
services/commun-types-disability/index.html
services/index.html

Fixed breadcrumb links (index-en.html -> index.html)
closes #32

issue 32 fix

---

learning/coaching/accessibility_coaching_series_v2/index.html

Reverts bati-itao/bati-itao.github.io#37

Revert "slide show updates"

---

services/commun-types-disability/index-fr.html
services/commun-types-disability/index.html

https://bati-itao.github.io/services/commun-types-disability/index.html

Intro line added to common disabilities pages

---

learning/coaching/accessibility-en.html
learning/coaching/accessibility-fr.html

Changed email to refer to the Request Management Tool on Accessibility coaching page

---

resources/proposed-meeting-types-accessibility-features-en.html
resources/proposed-meeting-types-accessibility-features-fr.html

Updated MS Teams meeting limit number on Proposed Meeting Type page

Updated MS Teams meeting limit number on Proposed Meeting Type page

---

resources/accessible-documents-en.html
resources/accessible-documents-fr.html

Added links in issue #168 as requested.

Added new links to accessible documents page

---

resources/ms-doc-compliance-checklist-en.html
resources/ms-doc-compliance-checklist-fr.html

Updated MS document compliance checklist

---

learning/self-paced-training-courses/index.html

Added hidden self-paced tutorials page

Added hidden self-paced tutorials page 

---

learning/self-paced-training-courses/index.html

Implemented noindex and changed page title and description

Implemented noindex and changed page title and description

---

learning/awareness/index-fr.html
learning/awareness/index.html

added margin between block elements on awareness events page.

Awareness events

---

learning/awareness/index-fr.html
learning/awareness/index.html

Created 2 columns layout for Awareness events

Created 2 columns layout for Awareness events

---

learning/self-paced-training-courses/decorative-redundant-images.html
learning/self-paced-training-courses/images-concepts.html
learning/self-paced-training-courses/index.html
learning/self-paced-training-courses/informative-images.html
learning/self-paced-training-courses/module05-images.html

1. Changed secondary menu on self-paced-training content pages
2. Added table of contents to self-paced training pages
3. Removed current page breadcrumb

Updated Self paced training pages

---

resources/Official-languages-recommendations-en.html
resources/Official-languages-recommendations-fr.html
resources/accessible-meeting-event-guidelines-en.html
resources/accessible-meeting-event-guidelines-fr.html
resources/events-en.html
resources/events-fr.html

Fixed broken URL official-languages-recommendatins-en.html and -fr

Fixed broken URL official-languages-recommendatins-en.html and -fr

---

teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

* WIP:Adding information for Andrew Nordlund on the Teams page.
* Added Information for Andrew Nordlund on Teams page.
* Fixed some typos on the Teams page for Andrew Nordlund.

Adding info on Teams Page for Andrew Nordlund (#1)

---

resources/wcag-en.html

Resolved issues mentionned in ticket 198

---

learning/awareness/awareness-days-fr.html
learning/awareness/awareness-days-goc-fr.html
learning/awareness/awareness-days-goc.html
learning/awareness/awareness-days.html

I change a few title events in French. 
I thought I clean what events go into the GOC page and awareness day page (English section). 
Still waiting for the missing content

Content ajustement in EN-FR

---

learning/esdc-self-paced-web-accessibility-course/content-structure.html
learning/esdc-self-paced-web-accessibility-course/landmarks.html

Replaced curly quotes with straight quotes in two files.

Curly to straight quotes

---

learning/esdc-self-paced-web-accessibility-course/Module01-Accessibility-Fundamentals.html
learning/esdc-self-paced-web-accessibility-course/Module02-Page-Structure-and-Semantics.html
learning/esdc-self-paced-web-accessibility-course/accessibility-guidelines.html
learning/esdc-self-paced-web-accessibility-course/best-practice.html
learning/esdc-self-paced-web-accessibility-course/content-structure.html
learning/esdc-self-paced-web-accessibility-course/decorative-redundant-images.html
learning/esdc-self-paced-web-accessibility-course/iframes.html
learning/esdc-self-paced-web-accessibility-course/images-concepts.html
learning/esdc-self-paced-web-accessibility-course/informative-images.html
learning/esdc-self-paced-web-accessibility-course/landmarks.html
learning/esdc-self-paced-web-accessibility-course/language.html
learning/esdc-self-paced-web-accessibility-course/laws-and-government-standards.html
learning/esdc-self-paced-web-accessibility-course/lists.html
learning/esdc-self-paced-web-accessibility-course/parsing-and-validity.html
learning/esdc-self-paced-web-accessibility-course/types-of-disabilities.html
learning/esdc-self-paced-web-accessibility-course/web-accessibility.html

All words in headings set to lowercase except the first, proper nouns, and the word following a colon.

Sentence case

---

learning/esdc-self-paced-web-accessibility-course/types-of-disabilities-seizure-em-update.html

In Module 1 under the section Seizures, updated the inline emphasis <em>any</em>.

Mod 1 - updated with em under Seizures

---

learning/esdc-self-paced-web-accessibility-course/types-of-disabilities.html

Fixed the following issues in the 3 video sections:
- fixed broken links (replaced youtube watch link with embed link)
- replaced list elements with paragraph elements in video 2
- moved source paragraph elements to after the videos
- removed duplicate iframe youtube container and fixed the source citation in video 2
- removed Microsoft Stream link from all 3 videos
- minor content edits in video 2

Fixed issues in the 3 video sections

---

learning/esdc-self-paced-web-accessibility-course/module2/landmarks.html

Update landmark section - removed the work 'ARIA'

aria removed from landmark

---

learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities.html

revised changes to em complete.

em revised changes

---

learning/esdc-self-paced-web-accessibility-course/module2/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module2/headings.html
learning/esdc-self-paced-web-accessibility-course/module2/iframes.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks.html
learning/esdc-self-paced-web-accessibility-course/module2/language.html
learning/esdc-self-paced-web-accessibility-course/module2/lists.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity.html

Set module menu link in sentence case: "Content Structure" to "Content structure"

Sentence case link in module menu

---

learning/esdc-self-paced-web-accessibility-course/module2/content-structure.html
learning/esdc-self-paced-web-accessibility-course/module2/lists.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity.html

Two files had short paths to two js and a css file. Added "../"
Set two headings to sentence case.

updated paths to js and CSS

---

learning/esdc-self-paced-web-accessibility-course/module2/content-structure.html

Strong and em on the Content Structure has been updated.

Content Structure strong and em updated

---

learning/esdc-self-paced-web-accessibility-course/module1/accessibility-guidelines-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/accessibility-guidelines.html
learning/esdc-self-paced-web-accessibility-course/module1/laws-and-government-standards-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities.html
learning/esdc-self-paced-web-accessibility-course/module1/web-accessibility-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/web-accessibility.html

Fixed module1 left menu in French broken links

Fixed module1 left menu in French broken links

---

learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities-fr.html

hanged menuPath from menu-en.html to menu-fr.html on types-of-disabilities-fr.html

Changed menuPath from menu-en.html to menu-fr.html 

---

learning/esdc-self-paced-web-accessibility-course/module2/headings.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks.html
learning/esdc-self-paced-web-accessibility-course/module2/language.html

Adds a few code tags and repairs the path the syntax highlighter CSS in a couple of files.

Code tags and path to highlight.css

---

learning/esdc-self-paced-web-accessibility-course/module2/content-structure.html
learning/esdc-self-paced-web-accessibility-course/module2/headings.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity.html

Fixed link text in menu and previous/next button

A few links to sentence case

---

learning/esdc-self-paced-web-accessibility-course/module1/accessibility-guidelines.html
learning/esdc-self-paced-web-accessibility-course/module1/laws-and-government-standards.html
learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities-seizure-em-update.html
learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities.html
learning/esdc-self-paced-web-accessibility-course/module1/web-accessibility.html

A few more links to sentence case

Links to sentence case

---

learning/esdc-self-paced-web-accessibility-course/module5/decorative-redundant-images.html
learning/esdc-self-paced-web-accessibility-course/module5/images-concepts.html
learning/esdc-self-paced-web-accessibility-course/module5/informative-images.html

Fixed module 5 left menu links

---

learning/esdc-self-paced-web-accessibility-course/module1/accessibility-guidelines.html
learning/esdc-self-paced-web-accessibility-course/module1/laws-and-government-standards.html
learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities.html
learning/esdc-self-paced-web-accessibility-course/module2/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks.html
learning/esdc-self-paced-web-accessibility-course/module2/language.html
learning/esdc-self-paced-web-accessibility-course/module2/lists.html

Nested ul lists in several files
Changed to ul to ol lists in guidelines.html
Added strong tags to list definitions

nesting lists

---

learning/esdc-self-paced-web-accessibility-course/module2/lists.html

Text in the second list of items is fixed.

fixed the text in the list items

---

learning/esdc-self-paced-web-accessibility-course/module2/headings.html

Visually hidden comments to code added to the heading file.

code comments added to headings file

---

services/accessibility-advice-compliance-fr.html
services/index-fr.html
services/service-standards-fr.html

Fixed issue #227 on Services French pages

Fixed issue #227 on Services French pages

---

learning/awareness/articles-2021-fr.html
learning/awareness/articles-2022-fr.html
learning/awareness/awareness-days-fr.html
learning/awareness/awareness-days-goc-fr.html
learning/awareness/awareness-event-fr.html
learning/awareness/index-fr.html
learning/awareness/training-fr.html

Fixed issue #227 on learning/awareness French pages

Fixed issue #227 on learning/awareness French pages

---

learning/esdc-self-paced-web-accessibility-course/module2/content-structure.html
learning/esdc-self-paced-web-accessibility-course/module2/language.html
learning/esdc-self-paced-web-accessibility-course/module2/lists.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity.html

Invisible comments on all Mod 2 files before <pre> are added.

all invsible comments added

---

learning/coaching/accessibility-fr.html
learning/coaching/feedback-fr.html
learning/coaching/index-fr.html
learning/coaching/quiz-fr.html
learning/coaching/session-references-fr.html
learning/coaching/software-fr.html
learning/coaching/thankyou-fr.html

Fixed issue #227 on learning/coaching French pages

Fixed issue #227 on learning/coaching French pages

---

learning/curriculum/desktop-application-developer-fr.html
learning/curriculum/desktop-application-tester-fr.html
learning/curriculum/general-accessibility-fr.html
learning/curriculum/index-fr.html
learning/curriculum/web-application-developer-fr.html
learning/curriculum/web-application-tester-fr.html
learning/curriculum/writers-editors-translators-fr.html

Fixed issue #227 on learning/curriculum/ French pages

Fixed issue #227 on learning/curriculum/ French pages

---

projects/_template-fr.html
projects/index-fr.html

Fixed issue #227 on projects/ French pages

Fixed issue #227 on projects/ French pages

---

_template-fr.html
teams/svatic-ictaas/index-fr.html

Fixed issue #227 on teams/svatic-ictaas/ French pages

Fixed issue #227 on teams/svatic-ictaas/ French pages

---

learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities-fr-old.html
learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities-fr.html

Merged fixes
- from the english page types-of-disabilities.html
- to the french page types-of-disabilities-fr.html
Updated line 18 to point to wet-fr.js

merged fixes into types-of-disabilities-fr.html

---

learning/esdc-self-paced-web-accessibility-course/module1/accessibility-guidelines-fr-old.html
learning/esdc-self-paced-web-accessibility-course/module1/accessibility-guidelines-fr.html

- merged english html fixes into accessibility-guidelines-fr.html
- edited line 19 to wet-fr.js

merged english html fixes into accessibility-guidelines-fr.html

---

learning/esdc-self-paced-web-accessibility-course/index-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/index-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks-fr.html

created module 2 landmarks-fr.html and index-fr.html

created mod 2 landmarks-fr.html and index-fr.html

---

learning/esdc-self-paced-web-accessibility-course/module2/headings-fr.html

created module 2 headings-fr.html

created module 2 headings-fr.html

---

learning/esdc-self-paced-web-accessibility-course/index-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/accessibility-guidelines-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/index-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks-fr.html

Guidelines

---

learning/esdc-self-paced-web-accessibility-course/module2/content-structure-fr.html

created module 2 - content-structure-fr.html

created module 2 - content-structure-fr.html

---

learning/esdc-self-paced-web-accessibility-course/module2/landmarks-fr.html

Landmark page converted to French

Landmark French Page

---

learning/esdc-self-paced-web-accessibility-course/module1/laws-and-government-standards-fr.html

nav indenting

---

learning/esdc-self-paced-web-accessibility-course/module1/accessibility-guidelines-fr.html

Section links were to English files

nav hrefs updated with -fr

---

learning/esdc-self-paced-web-accessibility-course/module1/laws-and-government-standards-fr.html

It's a mystery how this text ended up in this section. Don't know the source of it.

Replaced Canada Act section

---

learning/esdc-self-paced-web-accessibility-course/module2/headings-fr.html

Heading-fr changes have been completed.

Heading-fr changes done

---

learning/esdc-self-paced-web-accessibility-course/module2/language-fr.html

created module 2 - language-fr.html

created language-fr.html

---

learning/esdc-self-paced-web-accessibility-course/module2/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/content-structure-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/iframes-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/index-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/language-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/lists-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity-fr.html

Created new french template pages in module 2:
- lists-fr.html
- iframes-fr.html
- parsing-and-validity-fr.html
- best-practice-fr.html
Fixed broken links and other edits in french pages in module 2.

Module 2 - created new french templates and modified french pages

---

learning/esdc-self-paced-web-accessibility-course/module2/landmarks-fr.html

Update Landmarks Table of Content to French.

Landmark Table of Contents update

---

learning/esdc-self-paced-web-accessibility-course/module2/language-fr.html

Language section updated with French content.

French update to language section

---

learning/esdc-self-paced-web-accessibility-course/module2/headings-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/headings.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks.html
learning/esdc-self-paced-web-accessibility-course/module2/language.html

Added TOC and a "Designing with headings" h2 to headings (both lang)
Removed "navigation" from the nav aria-label

heading, toc, markup tweaks

---

learning/esdc-self-paced-web-accessibility-course/module2/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module2/content-structure.html
learning/esdc-self-paced-web-accessibility-course/module2/headings.html
learning/esdc-self-paced-web-accessibility-course/module2/iframes.html
learning/esdc-self-paced-web-accessibility-course/module2/index.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks.html
learning/esdc-self-paced-web-accessibility-course/module2/language.html
learning/esdc-self-paced-web-accessibility-course/module2/lists.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity.html

updated mod 2 english pages - french version link

updated mod 2 english pages - french version link

---

learning/esdc-self-paced-web-accessibility-course/module2/lists-fr.html

List French page update complete.

List French page updated

---

learning/esdc-self-paced-web-accessibility-course/module2/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module2/content-structure.html
learning/esdc-self-paced-web-accessibility-course/module2/headings.html
learning/esdc-self-paced-web-accessibility-course/module2/iframes.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks.html
learning/esdc-self-paced-web-accessibility-course/module2/language.html
learning/esdc-self-paced-web-accessibility-course/module2/lists.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity.html

updated mod2 menu links

---

learning/esdc-self-paced-web-accessibility-course/module2/content-structure-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/content-structure.html
learning/esdc-self-paced-web-accessibility-course/module2/headings-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/headings.html
learning/esdc-self-paced-web-accessibility-course/module2/iframes-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/iframes.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks.html
learning/esdc-self-paced-web-accessibility-course/module2/language-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/language.html
learning/esdc-self-paced-web-accessibility-course/module2/lists-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/lists.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity.html

in modules 1 and 2, both languages
Set the WCAG Resources heading as visually hidden with class="wb-inv"
Set criteria and techniques in a details/summary component

WCAG Resources set in details/summary

---

learning/esdc-self-paced-web-accessibility-course/module3/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module3/links.html
learning/esdc-self-paced-web-accessibility-course/module3/navigation.html

In module nav, set page title in sentence case and added aria-current on three pages.
Added code tags and nested lists in best-practices.html

code tags and module nav edit

---

learning/esdc-self-paced-web-accessibility-course/module3/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module3/index-fr.html
learning/esdc-self-paced-web-accessibility-course/module3/links-fr.html

created mod3 french pages index, links and best practices

created mod3 french pages index, links and best practices

---

learning/esdc-self-paced-web-accessibility-course/module3/navigation.html

Navigation English - updates

---

learning/esdc-self-paced-web-accessibility-course/module3/navigation.html

A minor edit added id attribute to a link.

Navigation English add id attribute

---

learning/esdc-self-paced-web-accessibility-course/module3/navigation.html

Mod 3 - Nav items in the list is indented.

nav items indented

---

teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

Translated Omar's title and professional IT certifications into French

Translated Omar's title and professional IT certifications into French

---

resources/bookmarks-fr.html
resources/bookmarks.html

I work on this issue: https://github.com/bati-itao/bati-itao.github.io/issues/124 
Everything should be good

issue-124-useful-links

---

learning/esdc-self-paced-web-accessibility-course/module3/navigation-fr.html

created mod3 navigation-fr.html

created mod3 navigation-fr.html

---

learning/esdc-self-paced-web-accessibility-course/module3/best-practice-fr.html

Couple of minor updates in Mod 3 French Best Practices section.

Minor updates in Fr Mod3 BP

---

learning/esdc-self-paced-web-accessibility-course/module5/index.html

Mod 5 - Sentence Case fixed on Index.html file

Sentence Case Fixed on Index in Mod5

---

learning/esdc-self-paced-web-accessibility-course/module1/web-accessibility.html
scripts/preFooter2.min.js

added feedback link to prefooter on web-accessibility page

added feedback link to prefooter on web-accessibility page

---

learning/esdc-self-paced-web-accessibility-course/module5/functional-images.html

added functional-images.html

---

learning/esdc-self-paced-web-accessibility-course/module1/accessibility-guidelines-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/accessibility-guidelines.html
learning/esdc-self-paced-web-accessibility-course/module1/index-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/index.html
learning/esdc-self-paced-web-accessibility-course/module1/laws-and-government-standards-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/laws-and-government-standards.html
learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities.html
learning/esdc-self-paced-web-accessibility-course/module1/web-accessibility-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/web-accessibility.html

Meta description in English for module 1 of ESDC Self Paced Web Accessibility Course

Module 1: Meta description in English

---

learning/esdc-self-paced-web-accessibility-course/module5/images-concepts.html

Updated the Image Concept file with header changes.

Image Conceps Page Updated

---

learning/esdc-self-paced-web-accessibility-course/module2/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module2/content-structure-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/content-structure.html
learning/esdc-self-paced-web-accessibility-course/module2/headings-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/headings.html
learning/esdc-self-paced-web-accessibility-course/module2/iframes-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/iframes.html
learning/esdc-self-paced-web-accessibility-course/module2/index-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/index.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks.html
learning/esdc-self-paced-web-accessibility-course/module2/language-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/language.html
learning/esdc-self-paced-web-accessibility-course/module2/lists-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/lists.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity.html

Meta description in English for module 2 of ESDC Self Paced Web Accessibility Course

M2: Meta Description in EN

---

learning/esdc-self-paced-web-accessibility-course/module5/decorative-redundant-images.html
learning/esdc-self-paced-web-accessibility-course/module5/informative-images.html

Informative Images page updated with revised header

Informative Images page update

---

learning/esdc-self-paced-web-accessibility-course/module5/decorative-redundant-images.html

Redundant Images Page is updated with latest transformation changes.

Redundant Images Page Update

---

learning/esdc-self-paced-web-accessibility-course/module1/web-accessibility.html
learning/esdc-self-paced-web-accessibility-course/module2/content-structure.html
learning/esdc-self-paced-web-accessibility-course/module5/complex-images.html

Edited complex-images.html
Fixed duplicate feedback link in web-accessibility.html
Fixed code indents in content-structure.html

complex-images.html and tweaks to two files

---

learning/esdc-self-paced-web-accessibility-course/module5/decorative-redundant-images.html

Mod 5 - minor text update Decorative to Designing.

Minor text update in Mod 5

---

index-fr.html
index.html

Spinoff of wet-boew/cdts-sgdc#245's PS message.

Index: Remove redundant H2 headings

---

learning/esdc-self-paced-web-accessibility-course/module5/functional-images.html
learning/esdc-self-paced-web-accessibility-course/module5/groups-images.html
learning/esdc-self-paced-web-accessibility-course/module5/images-text.html
learning/esdc-self-paced-web-accessibility-course/module5/images/Canada_Stop_sign.svg
learning/esdc-self-paced-web-accessibility-course/module5/svg-images.html

edited svg images
corrected misspelling of class="img-responsive"

svg images and fixed class name

---

teams/svatic-ictaas/index-en.html

Made the social media icons accessible on teams English page.

Made the social media icons accessible 

---

teams/svatic-ictaas/index-en.html

Removed visual hidden class wb-inv from some profiles

Removed visual hidden class wb-inv from some profiles

---

learning/esdc-self-paced-web-accessibility-course/module5/decorative-redundant-images.html
learning/esdc-self-paced-web-accessibility-course/module5/images-text.html

Mod 5 - Images of text image path corrected.

Mod5-Images of text image path corrected

---

teams/svatic-ictaas/index-fr.html

Made the social media icons accessible on French teams page

Made the social media icons accessible on French teams page

---

learning/esdc-self-paced-web-accessibility-course/index.html
learning/esdc-self-paced-web-accessibility-course/module7/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module7/colour.html
learning/esdc-self-paced-web-accessibility-course/module7/contrast.html
learning/esdc-self-paced-web-accessibility-course/module7/css-generated.html
learning/esdc-self-paced-web-accessibility-course/module7/hiding-content.html
learning/esdc-self-paced-web-accessibility-course/module7/index.html
learning/esdc-self-paced-web-accessibility-course/module7/introduction.html
learning/esdc-self-paced-web-accessibility-course/module7/page_template.html
learning/esdc-self-paced-web-accessibility-course/module7/textspacing.html
learning/esdc-self-paced-web-accessibility-course/module7/visual-proximity.html

created module 7 template files

created module 7 template files

---

learning/esdc-self-paced-web-accessibility-course/module8/index.html
learning/esdc-self-paced-web-accessibility-course/module8/introduction.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-design.html
learning/esdc-self-paced-web-accessibility-course/module8/zoom.html

created module 8 template files part 1

created module 8 template files part 1

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-forms.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-images.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-text.html

created 
responsive-forms.html
responsive-images.html
responsive-text.html

created mod 8 template files part 2

---

learning/esdc-self-paced-web-accessibility-course/module5/figcaption.html

added figcaption.html

---

learning/esdc-self-paced-web-accessibility-course/module8/introduction.html

Mod8 - Changes to the Intro section done.

Mod8 - Intro section changes

---

learning/esdc-self-paced-web-accessibility-course/module8/zoom.html

Mod8 - Zoom changes are completed.

Mod8 Zoom changes

---

learning/esdc-self-paced-web-accessibility-course/module5/alt-decision-tree.html
learning/esdc-self-paced-web-accessibility-course/module5/animated-images.html
learning/esdc-self-paced-web-accessibility-course/module5/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module5/complex-images.html
learning/esdc-self-paced-web-accessibility-course/module5/functional-images.html
learning/esdc-self-paced-web-accessibility-course/module5/groups-images.html
learning/esdc-self-paced-web-accessibility-course/module5/image-maps.html
learning/esdc-self-paced-web-accessibility-course/module5/index-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/index.html
learning/esdc-self-paced-web-accessibility-course/module5/informative-images.html
learning/esdc-self-paced-web-accessibility-course/module5/svg-images.html
learning/esdc-self-paced-web-accessibility-course/module5/text-alternatives.html
learning/esdc-self-paced-web-accessibility-course/module5/tips-and-tricks.html

Most Mod5 pages had a generic title or the mod3 title.

Fixed title element in mod5 files

---

learning/esdc-self-paced-web-accessibility-course/module8/introduction.html

Mod8 - Intro a paragraph has been added to this section

Mod8-intro added paragraph

---

learning/esdc-self-paced-web-accessibility-course/module5/decorative-redundant-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/functional-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/informative-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/text-alternatives-fr.html

created 4 mod5 french pages:
- text-alternatives-fr
- informative-images-fr
- functional-images-fr
- decorative-redudant-images-fr

created 4 mod5 french pages

---

teams/svatic-ictaas/index-fr.html

Removed .wb-inv from profil

---

learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities.html
learning/esdc-self-paced-web-accessibility-course/module4/additional-tips-and-tricks.html
learning/esdc-self-paced-web-accessibility-course/module4/caption-summary.html

edited additional-tips-and-tricks and caption-summary

vetted tips and caption-summary

---

learning/esdc-self-paced-web-accessibility-course/module4/tables-concepts.html

Bullets and paragraph fixed in Table concepts page.

Table Concepts bullets fix

---

learning/esdc-self-paced-web-accessibility-course/module4/tables-concepts.html

In Mod 4 - Table Concepts was missing the left nav - updated.

TC left menu was missing

---

learning/esdc-self-paced-web-accessibility-course/module7/colour.html
learning/esdc-self-paced-web-accessibility-course/module7/contrast.html
learning/esdc-self-paced-web-accessibility-course/module7/textspacing.html
learning/esdc-self-paced-web-accessibility-course/module7/visual-proximity.html

I change the colour header for the good and bad examples. 
I think they are all there, so I might have missed some.

Module 7 good-bad header

---

learning/awareness/articles-2021-fr.html
learning/awareness/articles-2021.html
learning/awareness/articles-2022-fr.html
learning/awareness/articles-2022.html
learning/awareness/awareness-days-fr.html
learning/awareness/awareness-days-goc-fr.html
learning/awareness/awareness-days-goc.html
learning/awareness/awareness-days.html
learning/awareness/awareness-event-fr.html
learning/awareness/awareness-event.html
learning/awareness/index-fr.html
learning/awareness/index.html
learning/awareness/training-fr.html
learning/awareness/training.html

- Added March Content
- Navigation Fixed

March Content Update Awareness Layout

---

learning/esdc-self-paced-web-accessibility-course/module3/links-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/colour-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/contrast-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/index-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/introduction-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/visual-proximity-fr.html

created mod 7 french templates:
-index
-introduction
-colour
-contrast

created mod 7 french templates

---

learning/esdc-self-paced-web-accessibility-course/module7/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/colour-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/colour.html
learning/esdc-self-paced-web-accessibility-course/module7/contrast-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/contrast.html
learning/esdc-self-paced-web-accessibility-course/module7/css-generated-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/css-generated.html
learning/esdc-self-paced-web-accessibility-course/module7/hiding-content-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/hiding-content.html
learning/esdc-self-paced-web-accessibility-course/module7/introduction.html

created mod7 french templates and fixed mod7 top menu nav link

created mod7 french templates

---

learning/esdc-self-paced-web-accessibility-course/module5/decorative-redundant-images-fr.html

Mod5 Redundant and Decorative Fr done.

Mod5 Redundant and Decorative Fr

---

learning/esdc-self-paced-web-accessibility-course/module5/functional-images-fr.html

Mod5 Functional Images for Fr completed.

Mod5 Functional Images Fr

---

learning/esdc-self-paced-web-accessibility-course/module5/animated-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/images-text-fr.html

created animated-images-fr

---

learning/esdc-self-paced-web-accessibility-course/module5/alt-decision-tree.html
learning/esdc-self-paced-web-accessibility-course/module5/animated-images.html
learning/esdc-self-paced-web-accessibility-course/module5/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module5/complex-images.html
learning/esdc-self-paced-web-accessibility-course/module5/decorative-redundant-images.html
learning/esdc-self-paced-web-accessibility-course/module5/figcaption.html
learning/esdc-self-paced-web-accessibility-course/module5/functional-images.html
learning/esdc-self-paced-web-accessibility-course/module5/groups-images.html
learning/esdc-self-paced-web-accessibility-course/module5/image-maps.html
learning/esdc-self-paced-web-accessibility-course/module5/images-text-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/images-text.html
learning/esdc-self-paced-web-accessibility-course/module5/informative-images.html
learning/esdc-self-paced-web-accessibility-course/module5/svg-images.html
learning/esdc-self-paced-web-accessibility-course/module5/text-alternatives.html
learning/esdc-self-paced-web-accessibility-course/module5/tips-and-tricks.html

Fixed all mod 5 files 
- breadcrumbs links
- footer links
- main nav links
- removed duplicate aria-labels

Fixed all mod 5 files - breadcrumbs and nav links

---

learning/esdc-self-paced-web-accessibility-course/module5/images-text-fr.html

Mod 5 - Images of Text French page complete.

Mod5 Images of Text French

---

learning/esdc-self-paced-web-accessibility-course/module5/animated-images-fr.html

Mod 5 - Animated Images French page complete.

Mod5 Animated Images Fr

---

learning/esdc-self-paced-web-accessibility-course/module5/alt-decision-tree-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/alt-decision-tree.html
learning/esdc-self-paced-web-accessibility-course/module5/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/complex-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/decorative-redundant-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/figcaption-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/functional-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/groups-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/image-maps-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/image-maps.html
learning/esdc-self-paced-web-accessibility-course/module5/images-text-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/index-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/informative-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/svg-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/text-alternatives-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/tips-and-tricks-fr.html

created remaining mod5 french page templates

created remaining mod5 french page templates

---

learning/esdc-self-paced-web-accessibility-course/module5/complex-images-fr.html

Complex images French complete.

Complex Images Fr

---

learning/esdc-self-paced-web-accessibility-course/module5/complex-images-fr.html

Mod5 - Complex Images Table Shading added.

Mod5 complex Images table shading

---

learning/esdc-self-paced-web-accessibility-course/module5/complex-images-fr.html

Mod5 - CI - a minor fix on the incoming file.

Mod5-CI-a minor fix

---

learning/esdc-self-paced-web-accessibility-course/module0/a_01.html
learning/esdc-self-paced-web-accessibility-course/module0/a_02.html
learning/esdc-self-paced-web-accessibility-course/module0/a_03.html
learning/esdc-self-paced-web-accessibility-course/module0/a_04.html
learning/esdc-self-paced-web-accessibility-course/module0/a_05.html
learning/esdc-self-paced-web-accessibility-course/module0/a_06.html
learning/esdc-self-paced-web-accessibility-course/module0/a_07.html
learning/esdc-self-paced-web-accessibility-course/module0/a_08.html
learning/esdc-self-paced-web-accessibility-course/module0/a_09.html
learning/esdc-self-paced-web-accessibility-course/module0/a_10.html
learning/esdc-self-paced-web-accessibility-course/module0/index.html

- temporary files used to create page templates for other modules

module0 page template files

---

learning/esdc-self-paced-web-accessibility-course/module5/images-text-fr.html

Mod5 - Font size and format update in the WCAG and Techniques section.

Mod5 Font size update in techniques section

---

learning/esdc-self-paced-web-accessibility-course/module4/additional-tips-and-tricks.html
learning/esdc-self-paced-web-accessibility-course/module4/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module4/caption-summary.html
learning/esdc-self-paced-web-accessibility-course/module4/irregular-headers.html
learning/esdc-self-paced-web-accessibility-course/module4/multi-level-headers.html
learning/esdc-self-paced-web-accessibility-course/module4/one-header.html
learning/esdc-self-paced-web-accessibility-course/module4/tables-concepts.html
learning/esdc-self-paced-web-accessibility-course/module4/tables-resources.html
learning/esdc-self-paced-web-accessibility-course/module4/two-headers.html

fixed mod4 left nav, top nav, bottom footer and feedback link

fixed mod4 left nav, top nav, bottom footer and feedback link

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-text.html

added aria-labelledby to responsive-text.html

added aria-labelledby to responsive-text.html

---

learning/esdc-self-paced-web-accessibility-course/module5/groups-images-fr.html

Mod5 Groups of Images Fr

---

learning/esdc-self-paced-web-accessibility-course/module5/image-maps-fr.html

Mod 5 - Image Maps French Complete.

Mod 5 - Image Maps French

---

learning/esdc-self-paced-web-accessibility-course/module5/svg-images.html

Mod 5 - SVG English Container Added

Mod 5 SVG Eng Container added

---

learning/esdc-self-paced-web-accessibility-course/module5/svg-images-fr.html

Mod 5 SVG Changes to FR added Container

Mod5 SVG FR Container

---

learning/esdc-self-paced-web-accessibility-course/module5/alt-decision-tree.html

Added container to Mod5 Alt Txt English.

Mod5 Alt Text EN  container added

---

learning/esdc-self-paced-web-accessibility-course/module3/links-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/additional-tips-and-tricks-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/irregular-headers-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/irregular-headers.html
learning/esdc-self-paced-web-accessibility-course/module4/multi-level-headers-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/one-header-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/tables-concepts-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/tables-resources-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/two-headers-fr.html

French added to:
- tables-concepts-fr
- one-header-fr
- two-header-fr
- irregular-headers-fr
Nav link fixed in other mod4 files

mod4 French files

---

learning/esdc-self-paced-web-accessibility-course/module5/svg-images-fr.html

Mod5 SVG Fr update

---

learning/esdc-self-paced-web-accessibility-course/module4/best-practice-fr.html

Mod 4 - Best Practices FR complete.

Mod4 Best Practices FR

---

learning/esdc-self-paced-web-accessibility-course/module4/tables-resources-fr.html

Mod4 WET Table Resources FR Update complete

Mod4 WET Table Resources FR update

---

learning/esdc-self-paced-web-accessibility-course/module4/additional-tips-and-tricks-fr.html

Mod 4 - Additional Tips and Tricks Fr updates complete.

Mod4 Additional Tips and Tricks FR

---

learning/esdc-self-paced-web-accessibility-course/module4/caption-summary-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/caption-summary.html
learning/esdc-self-paced-web-accessibility-course/module4/multi-level-headers-fr.html

Two files in french and a tweak to caption-summary English

French caption-summary and multi-level-headers

---

learning/esdc-self-paced-web-accessibility-course/module4/best-practice-fr.html

Mod4 - Best Practices a few minor updates.

Mod4 Best Practices minor updates

---

learning/esdc-self-paced-web-accessibility-course/module4/additional-tips-and-tricks-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/caption-summary-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/irregular-headers-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/irregular-headers.html
learning/esdc-self-paced-web-accessibility-course/module4/multi-level-headers.html
learning/esdc-self-paced-web-accessibility-course/module4/tables-concepts-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/tables-concepts.html
learning/esdc-self-paced-web-accessibility-course/module4/two-headers-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/two-headers.html

mod4 minor edits

---

learning/awareness/articles-2022-fr.html
learning/awareness/articles-2022.html

Article 2022 link fix

---

learning/esdc-self-paced-web-accessibility-course/module8/introduction.html

Mod 8 - An id is added to the Intro section in English.

Mod 8 Intro English id added

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-design.html

Mod 8 - Responsive design container and view code update

Mod8 Responsive design container update

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-design.html

Mod8 Responsive Design headers updated.

Mod8 RD headers update

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-images.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-text.html

Mod 8 Responsive Text updates complete.

Mod 8 Responsive Text

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-objects.html

Mod8 Responsive Object and Plugins page update

Mod8 Responsive Objects and Plugins update

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-objects.html

Mod 8 Objects and Plugin header updated

Mod 8 Objects and Plugin header updated

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-ui.html

Mod8 Responsive UI page complete.

Mod8 Responsive UI

---

learning/esdc-self-paced-web-accessibility-course/module3/navigation.html
learning/esdc-self-paced-web-accessibility-course/module7/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module7/colour-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/contrast-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/contrast.html
learning/esdc-self-paced-web-accessibility-course/module7/css-generated-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/css-generated.html
learning/esdc-self-paced-web-accessibility-course/module7/hiding-content-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/hiding-content.html
learning/esdc-self-paced-web-accessibility-course/module7/introduction-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/textspacing-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/textspacing.html
learning/esdc-self-paced-web-accessibility-course/module7/visual-proximity-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/visual-proximity.html

all mod 7 files reviewed. 
And a tweak to mod 3 navigation.html

mod7 vetting in en/fr

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-ui.html

Mod8 RUI id correction re-pushed.

Mod8 RUI id correction

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-ui.html

Mod8 Responsive UI id removed.

Mod8 RUI removed id

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-objects.html

Mod8 Responsive Objects and Plugins id added.

Mod8-RObjects id added

---

learning/esdc-self-paced-web-accessibility-course/module2/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module2/content-structure-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/content-structure.html
learning/esdc-self-paced-web-accessibility-course/module2/headings-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/headings.html
learning/esdc-self-paced-web-accessibility-course/module2/iframes-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/iframes.html
learning/esdc-self-paced-web-accessibility-course/module2/index-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks.html
learning/esdc-self-paced-web-accessibility-course/module2/language-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/language.html
learning/esdc-self-paced-web-accessibility-course/module2/lists-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/lists.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity.html
learning/esdc-self-paced-web-accessibility-course/module3/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module3/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module3/index-fr.html
learning/esdc-self-paced-web-accessibility-course/module3/links-fr.html
learning/esdc-self-paced-web-accessibility-course/module3/links.html
learning/esdc-self-paced-web-accessibility-course/module3/navigation-fr.html
learning/esdc-self-paced-web-accessibility-course/module3/navigation.html

fixed mod2 and mod3 left nav, breadcrumb and footer links

fixed mod2 and mod3 left nav, breadcrumb and footer links

---

scripts/preFooter2-fr.min.js

updated french feedback link URL in script

updated french feedback link URL in script

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-video.html

Mod8 Responsive Video page complete.

Mod8 Responsive video

---

learning/esdc-self-paced-web-accessibility-course/module8/orientation.html

Mod8 Orientation Page complete.

Mod8 orientation page

---

learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities.html
learning/esdc-self-paced-web-accessibility-course/module2/headings-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/headings.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks.html
learning/esdc-self-paced-web-accessibility-course/module2/lists.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity.html
learning/esdc-self-paced-web-accessibility-course/module3/navigation-fr.html
learning/esdc-self-paced-web-accessibility-course/module3/navigation.html

In preparation for adding "Example starts/ends" messages

Added example containers

---

learning/esdc-self-paced-web-accessibility-course/index.html
learning/esdc-self-paced-web-accessibility-course/module1/index.html
learning/esdc-self-paced-web-accessibility-course/module2/index.html
learning/esdc-self-paced-web-accessibility-course/module3/index.html
learning/esdc-self-paced-web-accessibility-course/module6/index.html

Set headings and links in Sentence case in index files

Sentence case in index files

---

learning/esdc-self-paced-web-accessibility-course/module0/a_01.html
learning/esdc-self-paced-web-accessibility-course/module0/a_02.html
learning/esdc-self-paced-web-accessibility-course/module0/a_03.html
learning/esdc-self-paced-web-accessibility-course/module0/a_04.html
learning/esdc-self-paced-web-accessibility-course/module0/a_05.html
learning/esdc-self-paced-web-accessibility-course/module0/a_06.html
learning/esdc-self-paced-web-accessibility-course/module0/a_07.html
learning/esdc-self-paced-web-accessibility-course/module0/a_08.html
learning/esdc-self-paced-web-accessibility-course/module0/a_09.html
learning/esdc-self-paced-web-accessibility-course/module0/a_10.html
learning/esdc-self-paced-web-accessibility-course/module0/a_11.html
learning/esdc-self-paced-web-accessibility-course/module0/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module0/index.html
learning/esdc-self-paced-web-accessibility-course/module9/animation-motion.html
learning/esdc-self-paced-web-accessibility-course/module9/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module9/captions.html
learning/esdc-self-paced-web-accessibility-course/module9/description-visual.html
learning/esdc-self-paced-web-accessibility-course/module9/flashing-content.html
learning/esdc-self-paced-web-accessibility-course/module9/index.html
learning/esdc-self-paced-web-accessibility-course/module9/introduction.html
learning/esdc-self-paced-web-accessibility-course/module9/media-player.html
learning/esdc-self-paced-web-accessibility-course/module9/pause-stop-hide.html
learning/esdc-self-paced-web-accessibility-course/module9/policy-matrix.html
learning/esdc-self-paced-web-accessibility-course/module9/sign-language.html
learning/esdc-self-paced-web-accessibility-course/module9/transcribing-audio.html
learning/esdc-self-paced-web-accessibility-course/module9/transcripts.html

created module 9 english template files

Mod9 template

---

learning/esdc-self-paced-web-accessibility-course/module9/introduction.html

Mod9 Introduction page

---

learning/esdc-self-paced-web-accessibility-course/module9/media-player.html

Mod 9 Multimedia player page update.

Mod9 Multimedia Player update

---

learning/esdc-self-paced-web-accessibility-course/module1/accessibility-guidelines-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/accessibility-guidelines.html
learning/esdc-self-paced-web-accessibility-course/module1/laws-and-government-standards-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/laws-and-government-standards.html
learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities.html
learning/esdc-self-paced-web-accessibility-course/module1/web-accessibility-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/web-accessibility.html

Meta description for mod 1

---

learning/esdc-self-paced-web-accessibility-course/module1/accessibility-guidelines-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/accessibility-guidelines.html
learning/esdc-self-paced-web-accessibility-course/module1/laws-and-government-standards-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/laws-and-government-standards.html
learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities.html
learning/esdc-self-paced-web-accessibility-course/module1/web-accessibility-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/web-accessibility.html
learning/esdc-self-paced-web-accessibility-course/module2/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module2/content-structure-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/content-structure.html
learning/esdc-self-paced-web-accessibility-course/module2/headings-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/headings.html
learning/esdc-self-paced-web-accessibility-course/module2/iframes-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/iframes.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks.html
learning/esdc-self-paced-web-accessibility-course/module2/language-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/language.html
learning/esdc-self-paced-web-accessibility-course/module2/lists-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/lists.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity.html

Meta description mod 2

---

learning/esdc-self-paced-web-accessibility-course/module3/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module3/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module3/links-fr.html
learning/esdc-self-paced-web-accessibility-course/module3/links.html
learning/esdc-self-paced-web-accessibility-course/module3/navigation-fr.html
learning/esdc-self-paced-web-accessibility-course/module3/navigation.html

meta description for mod 3

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-images.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-tables.html

Removed colon in alt text

---

learning/esdc-self-paced-web-accessibility-course/module5/alt-decision-tree-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/alt-decision-tree.html
learning/esdc-self-paced-web-accessibility-course/module5/animated-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/animated-images.html
learning/esdc-self-paced-web-accessibility-course/module5/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module5/complex-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/complex-images.html
learning/esdc-self-paced-web-accessibility-course/module5/decorative-redundant-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/decorative-redundant-images.html
learning/esdc-self-paced-web-accessibility-course/module5/figcaption-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/figcaption.html
learning/esdc-self-paced-web-accessibility-course/module5/functional-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/functional-images.html
learning/esdc-self-paced-web-accessibility-course/module5/groups-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/groups-images.html
learning/esdc-self-paced-web-accessibility-course/module5/image-maps-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/image-maps.html
learning/esdc-self-paced-web-accessibility-course/module5/images-text-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/images-text.html
learning/esdc-self-paced-web-accessibility-course/module5/informative-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/informative-images.html
learning/esdc-self-paced-web-accessibility-course/module5/svg-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/svg-images.html
learning/esdc-self-paced-web-accessibility-course/module5/text-alternatives-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/text-alternatives.html
learning/esdc-self-paced-web-accessibility-course/module5/tips-and-tricks-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/tips-and-tricks.html

meta description for mod 5

---

learning/esdc-self-paced-web-accessibility-course/module6/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module6/custom-controls.html
learning/esdc-self-paced-web-accessibility-course/module6/form-instructions.html
learning/esdc-self-paced-web-accessibility-course/module6/forms-concepts.html
learning/esdc-self-paced-web-accessibility-course/module6/grouping-controls.html
learning/esdc-self-paced-web-accessibility-course/module6/identifying-input.html
learning/esdc-self-paced-web-accessibility-course/module6/labelling-controls.html
learning/esdc-self-paced-web-accessibility-course/module6/multi-step-forms.html
learning/esdc-self-paced-web-accessibility-course/module6/user-notifications.html
learning/esdc-self-paced-web-accessibility-course/module6/validating-input.html

meta description for mod 6
Index page and pages in FR aren't done

meta description for mod 6

---

learning/esdc-self-paced-web-accessibility-course/module7/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module7/colour-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/colour.html
learning/esdc-self-paced-web-accessibility-course/module7/contrast-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/contrast.html
learning/esdc-self-paced-web-accessibility-course/module7/css-generated-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/css-generated.html
learning/esdc-self-paced-web-accessibility-course/module7/hiding-content-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/hiding-content.html
learning/esdc-self-paced-web-accessibility-course/module7/introduction-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/introduction.html
learning/esdc-self-paced-web-accessibility-course/module7/textspacing-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/textspacing.html
learning/esdc-self-paced-web-accessibility-course/module7/visual-proximity-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/visual-proximity.html

meta description for mod 7

---

learning/esdc-self-paced-web-accessibility-course/module9/captions.html

Mod9 Captions page udpate

---

learning/esdc-self-paced-web-accessibility-course/module9/media-player.html

Mod9 Mplayer minor update

---

learning/esdc-self-paced-web-accessibility-course/module9/captions.html

Mod9 Captions page update - added definition list

Mod9 Captions page update - added definition list

---

learning/esdc-self-paced-web-accessibility-course/module9/captions.html

Mod 9 cap li updated

---

learning/esdc-self-paced-web-accessibility-course/module9/media-player.html

Mod 9 Media player page updated.

Mod 9 Media player page

---

learning/esdc-self-paced-web-accessibility-course/module9/flashing-content.html

Mod 9 Flashing Content Page updated.

Mod 9 Flashing content page

---

learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities.html
learning/esdc-self-paced-web-accessibility-course/module3/links.html
learning/esdc-self-paced-web-accessibility-course/module5/images-text.html
learning/esdc-self-paced-web-accessibility-course/module6/form-instructions.html
learning/esdc-self-paced-web-accessibility-course/module7/textspacing.html
learning/esdc-self-paced-web-accessibility-course/module7/visual-proximity.html
learning/esdc-self-paced-web-accessibility-course/module8/old-responsive-design.html
learning/esdc-self-paced-web-accessibility-course/module8/old-zoom.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-video.html
learning/esdc-self-paced-web-accessibility-course/module8/zoom.html
learning/esdc-self-paced-web-accessibility-course/module9/captions.html
learning/esdc-self-paced-web-accessibility-course/module9/description-visual.html

Set Good/Bad Example in sentence case

---

learning/esdc-self-paced-web-accessibility-course/module9/transcribing-audio.html

Mod9 Audio to Text page update.

Mod9 Audio to Text

---

learning/esdc-self-paced-web-accessibility-course/module9/introduction.html

Mod 9 introduction minor update to table of content.

Mod9 intro minor update

---

learning/esdc-self-paced-web-accessibility-course/module9/captions.html

Mod9 Captions html code format fixed.

Captions html code foramt fix

---

learning/esdc-self-paced-web-accessibility-course/module9/introduction.html

Mod 9 introduction items bold.

Mod 9 intro bold.

---

learning/esdc-self-paced-web-accessibility-course/module9/captions.html

Mod 9 Captions links reference added

Mod 9 Captions links reference added

---

learning/esdc-self-paced-web-accessibility-course/module9/captions.html

Mod9 Captions embed video and alt

Mod9 Captions embed video and alt

---

learning/esdc-self-paced-web-accessibility-course/module9/transcripts.html

Mod9 Transcript embed video and links. A transcript video.html file is created to satisfy an example of opening a transcript in a new window.

Mod9 Transcript embed video and links

---

learning/esdc-self-paced-web-accessibility-course/module9/transcripts.html

Mod9 transcirpt file

---

learning/esdc-self-paced-web-accessibility-course/module9/animation-motion.html

Mod9 Animation  link update

---

learning/esdc-self-paced-web-accessibility-course/module8/introduction-fr.html

Mod 8 introduction french page

Mod 8 introduction french page

---

learning/esdc-self-paced-web-accessibility-course/module8/zoom-fr.html

Mod 8 Zoom FR page

---

learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/orientation-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-design-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-forms-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-objects-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-tables-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-text-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-ui-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-video-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/zoom-fr.html

fixed mod1 and mod8 french breadcrumb and top nav

fixed mod1 and mod8 french breadcrumb and top nav

---

css/custom-table.css
learning/esdc-self-paced-web-accessibility-course/module9/description-visual.html
learning/esdc-self-paced-web-accessibility-course/module9/media-player.html
learning/esdc-self-paced-web-accessibility-course/module9/policy-matrix.html
learning/esdc-self-paced-web-accessibility-course/module9/sign-language.html
learning/esdc-self-paced-web-accessibility-course/module9/transcripts.html

Vetted:
description-visual
media-player
sign-language
Tweaked:
policy-matrix
transcripts
custom-table.css

mod 9 vetting several files

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-design-fr.html

Mod8 Responsive Design French page updated

Mod8 Responsive Design Fr updated

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-forms-fr.html

Mod8 Responsive Forms French

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-text-fr.html

Mod8 Responsive Text French

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-images-fr.html

Mod8 Responsive Images page update

Mod8 Responsive Images page update

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-objects-fr.html

Mod8 Objects and Plugins French page complete.

Mod8 Objects and Plugins French

---

learning/esdc-self-paced-web-accessibility-course/module9/best-practice-fr.html

Mod9 Best Practices French page complete.

Mod9 Best Practices French

---

learning/esdc-self-paced-web-accessibility-course/module9/pause-stop-hide-fr.html

Mod9 Pause Stop and Hide French page complete.

Mod9-PSH-FRENCH

---

learning/esdc-self-paced-web-accessibility-course/module9/flashing-content-fr.html

Mod 9 Flashing content FR

---

learning/esdc-self-paced-web-accessibility-course/module9/media-player-fr.html

Mod9 MPlayer French page complete

Mod9 MPlayer French

---

learning/esdc-self-paced-web-accessibility-course/module9/sign-language-fr.html

Mod9 Sign Language French complete

Mod9 Sign Language FR

---

learning/esdc-self-paced-web-accessibility-course/module9/description-visual-fr.html

Mod 9 Visual Information French complete.

Mod 9 Visual Information FR

---

learning/esdc-self-paced-web-accessibility-course/module9/captions-fr.html

Mod9-Captions French page complete

Mod9-Captions French page

---

learning/esdc-self-paced-web-accessibility-course/module9/captions-fr.html
learning/esdc-self-paced-web-accessibility-course/module9/introduction-fr.html

Mod 9 Introduction french page complete.

Mod 9 Introduction french

---

learning/esdc-self-paced-web-accessibility-course/module9/policy-matrix-fr.html

Mod 9 Multimedia French page complete.

Mod 9 Multimedia French page

---

learning/esdc-self-paced-web-accessibility-course/module9/captions-fr.html

Mod9 Captions a minor update on French page.

Mod9 Captions a minor update FR

---

learning/esdc-self-paced-web-accessibility-course/module10/introduction.html

Mod 10 Introduction page complete.

Mod 10 Introduction page

---

learning/esdc-self-paced-web-accessibility-course/module6/form-instructions.html
learning/esdc-self-paced-web-accessibility-course/module6/identifying-input.html
learning/esdc-self-paced-web-accessibility-course/module6/validating-input.html

halfway through validating-input
form-instructions
identifying-input

mod6 vetting two and a half files

---

learning/esdc-self-paced-web-accessibility-course/module10/mouse-input.html

Mod 10 Mouse Input english page complete.

Mod 10 Mouse Input Eng Page.

---

learning/esdc-self-paced-web-accessibility-course/module10/best-practice.html

Mod10 Best Practices page

---

learning/esdc-self-paced-web-accessibility-course/module10/motion-actuation.html

Mod10 Motion Actuation page complete.

Mod10 Motion Actuation EN

---

learning/esdc-self-paced-web-accessibility-course/module6/identifying-input.html
learning/esdc-self-paced-web-accessibility-course/module6/validating-input.html

added headings and changed tables to definition lists

mod6 vetting minor tweak to two files

---

learning/esdc-self-paced-web-accessibility-course/module6/validating-input.html

mod6 vetted validating-input

---

learning/esdc-self-paced-web-accessibility-course/module10/keyboard-input.html

Mod10 Keyboard Input English Page complete.

Mod10 Keyboard Input

---

learning/esdc-self-paced-web-accessibility-course/module10/touch-input.html

Mod10 Input Pointer page complete.

Mod10 Input Pointer page

---

learning/esdc-self-paced-web-accessibility-course/module10/voice-input.html

Mod10 Voice Input page complete.

Mod10 Voice Input page

---

learning/esdc-self-paced-web-accessibility-course/module10/mouse-input.html

Mod10 Mouse Input container updates

Mod10 Mouse Input container updates

---

learning/esdc-self-paced-web-accessibility-course/module10/keyboard-input.html

Mod10 Keyboard input link updates

Mod10 Keyboard input link updates

---

learning/esdc-self-paced-web-accessibility-course/module10/mouse-input.html

Mod10 mouse input update to WCAG link

Mod10 mouse input update to WCAG link

---

learning/esdc-self-paced-web-accessibility-course/module1/accessibility-guidelines-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/accessibility-guidelines.html
learning/esdc-self-paced-web-accessibility-course/module1/index-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/index.html
learning/esdc-self-paced-web-accessibility-course/module1/laws-and-government-standards-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/laws-and-government-standards.html
learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities.html
learning/esdc-self-paced-web-accessibility-course/module1/web-accessibility-fr.html
learning/esdc-self-paced-web-accessibility-course/module1/web-accessibility.html

Mod1 Crawler removed "noindex'

Mod1 Crawler removed

---

learning/esdc-self-paced-web-accessibility-course/module9/captions-fr.html

Mod9 Caption French Video links

Mod9 Caption French Video links

---

learning/esdc-self-paced-web-accessibility-course/module9/captions-fr.html

Mod 9 Captions French Video link update

Mod 9 Captions French Video link

---

learning/esdc-self-paced-web-accessibility-course/module2/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module2/content-structure-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/content-structure.html
learning/esdc-self-paced-web-accessibility-course/module2/headings-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/headings.html
learning/esdc-self-paced-web-accessibility-course/module2/iframes-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/iframes.html
learning/esdc-self-paced-web-accessibility-course/module2/index-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/index.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks.html
learning/esdc-self-paced-web-accessibility-course/module2/language-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/language.html
learning/esdc-self-paced-web-accessibility-course/module2/lists-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/lists.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity.html

Mod2 - noindex crawler removed

Mod2 - noindex crawler removed

---

learning/esdc-self-paced-web-accessibility-course/module3/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module3/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module3/index-fr.html
learning/esdc-self-paced-web-accessibility-course/module3/index.html
learning/esdc-self-paced-web-accessibility-course/module3/links-fr.html
learning/esdc-self-paced-web-accessibility-course/module3/links.html
learning/esdc-self-paced-web-accessibility-course/module3/navigation-fr.html
learning/esdc-self-paced-web-accessibility-course/module3/navigation.html

Mod3 noindex removed

---

learning/esdc-self-paced-web-accessibility-course/module4/additional-tips-and-tricks-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/additional-tips-and-tricks.html
learning/esdc-self-paced-web-accessibility-course/module4/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module4/caption-summary-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/caption-summary.html
learning/esdc-self-paced-web-accessibility-course/module4/index-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/index.html
learning/esdc-self-paced-web-accessibility-course/module4/irregular-headers-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/irregular-headers.html
learning/esdc-self-paced-web-accessibility-course/module4/multi-level-headers-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/multi-level-headers.html
learning/esdc-self-paced-web-accessibility-course/module4/one-header-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/one-header.html
learning/esdc-self-paced-web-accessibility-course/module4/tables-concepts-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/tables-concepts.html
learning/esdc-self-paced-web-accessibility-course/module4/tables-resources-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/tables-resources.html
learning/esdc-self-paced-web-accessibility-course/module4/two-headers-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/two-headers.html

Mod4- noindex removed

---

learning/esdc-self-paced-web-accessibility-course/module10/introduction-fr.html

Mod10 Introduction French

---

learning/esdc-self-paced-web-accessibility-course/module10/mouse-input-fr.html

Mod10 Mouse Input French page.

Mod10 Mouse Input Fr

---

learning/esdc-self-paced-web-accessibility-course/module10/keyboard-input-fr.html

Mod10 Keyboard Input French page.

Mod10 Keyboard Input French

---

learning/coaching/software-fr.html

Removed "Modules complémentaires de Firefox" on software-fr.html

Removed "Modules complémentaires de Firefox" on software-fr.html

---

learning/esdc-self-paced-web-accessibility-course/module10/best-practice-fr.html

Mod10 Best Practices French complete

Mod10 Best Practices French

---

learning/coaching/software-fr.html

Fixed misuse of <dl> element on software-fr.html

Fixed misuse of dl element on software-fr.html

---

learning/esdc-self-paced-web-accessibility-course/module10/voice-input-fr.html

Mod10 Voice Input French page complete.

Mod10 Voice Input French

---

learning/esdc-self-paced-web-accessibility-course/module10/motion-actuation-fr.html

Mod10 Motion Actuation added French

Mod10 Motion Actuation added French

---

learning/coaching/software-fr.html

Fixed HTML validation errors

---

learning/coaching/software-fr.html

Removed lang attribute as hreflang is already used

Removed lang attribute as hreflang is already used

---

learning/esdc-self-paced-web-accessibility-course/module10/touch-input-fr.html

Mod10 Touch Point Input French page complete

Mod10 Touch Point Input French

---

learning/esdc-self-paced-web-accessibility-course/module10/keyboard-input-fr.html

Mod10 Keyboard Input updated keyboard input section - French page

Mod10 Keyboard Input updated FR

---

learning/esdc-self-paced-web-accessibility-course/module6/forms-concepts-fr.html

Mod6 Forms Concepts French page update

Mod6 Forms Concepts French

---

learning/esdc-self-paced-web-accessibility-course/module6/labelling-controls-fr.html

Mod6- Labelling Control French page

Mod6 - labelling control french

---

learning/esdc-self-paced-web-accessibility-course/module6/labelling-controls-fr.html

Mod6 label control french complete

Mod6 label control french complete

---

learning/esdc-self-paced-web-accessibility-course/module11/aria-live.html
learning/esdc-self-paced-web-accessibility-course/module11/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module11/time-limits.html
learning/esdc-self-paced-web-accessibility-course/module3/links-fr.html

mod11 vetting

---

learning/esdc-self-paced-web-accessibility-course/module10/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module10/introduction-fr.html
learning/esdc-self-paced-web-accessibility-course/module10/introduction.html
learning/esdc-self-paced-web-accessibility-course/module10/keyboard-input-fr.html
learning/esdc-self-paced-web-accessibility-course/module10/keyboard-input.html
learning/esdc-self-paced-web-accessibility-course/module10/motion-actuation-fr.html
learning/esdc-self-paced-web-accessibility-course/module10/mouse-input-fr.html
learning/esdc-self-paced-web-accessibility-course/module10/mouse-input.html
learning/esdc-self-paced-web-accessibility-course/module10/touch-input-fr.html
learning/esdc-self-paced-web-accessibility-course/module10/voice-input-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/alt-decision-tree-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/alt-decision-tree.html
learning/esdc-self-paced-web-accessibility-course/module9/animation-motion.html
learning/esdc-self-paced-web-accessibility-course/module9/transcripts-fr.html

also fixed mod10-fr course navigation (wrong module was highlighted as active)

minor cleanup of mark flags

---

learning/esdc-self-paced-web-accessibility-course/module6/form-instructions-fr.html

Mod 6 Forms Instructions French, first update..

Mod 6 Forms Instructions French

---

learning/esdc-self-paced-web-accessibility-course/module6/form-instructions-fr.html

Mod6 Forms Iinstruction update French complete with TODO items

Mod6 Forms Iinstruction update French with some TODO checks

---

learning/esdc-self-paced-web-accessibility-course/module6/validating-input-fr.html

Mod6 Validating Input French page

Mod6 Validating Input French

---

learning/esdc-self-paced-web-accessibility-course/module6/form-instructions-fr.html

Mod6 Forms Instructions id fixes in French page

Mod6 Forms Instructions id fixes in French page

---

learning/esdc-self-paced-web-accessibility-course/module6/identifying-input-fr.html

Mod6 Identifying inputs French page complete with some TODO items

Mod6 Identifying inputs French page complete with some TODO items

---

learning/esdc-self-paced-web-accessibility-course/module6/validating-input-fr.html

Mod6 Validating Input updated FR page complete.

Mod6 Validating Input updated FR

---

learning/esdc-self-paced-web-accessibility-course/module6/best-practice-fr.html

Mod6 Best Practices French page complete

Mod6 Best Practices French

---

learning/esdc-self-paced-web-accessibility-course/module6/user-notifications-fr.html

Mod6 User notification French page complete

Mod6 User notification French page

---

learning/esdc-self-paced-web-accessibility-course/module6/multi-step-forms-fr.html

Mod6 Multi step form French page complete

Mod6 Multi step form FR

---

learning/esdc-self-paced-web-accessibility-course/module6/custom-controls-fr.html

Mod6 Custom Control French page complete.

Mod6 Custom Control French page

---

learning/esdc-self-paced-web-accessibility-course/module11/best-practice-fr.html

Mod11 Best Practices French page

Mod11 Best Practices French

---

learning/esdc-self-paced-web-accessibility-course/module11/time-limits-fr.html

Mod11 Time Limits French

---

learning/esdc-self-paced-web-accessibility-course/module11/aria-live-fr.html

Mod 11 Aria Live French Page

---

learning/esdc-self-paced-web-accessibility-course/module11/aria-live-fr.html

Mod11 Zone live ARIA French page  updates complete.

Mod11 Zone live ARIA French updates

---

learning/esdc-self-paced-web-accessibility-course/module11/time-limits-fr.html

Mod11-Time Limit id update French page.

Mod11-Time Limit update French

---

learning/esdc-self-paced-web-accessibility-course/module11/aria-live-fr.html
learning/esdc-self-paced-web-accessibility-course/module11/aria-live.html
learning/esdc-self-paced-web-accessibility-course/module11/example-countdown-fr.html
learning/esdc-self-paced-web-accessibility-course/module11/time-limits-fr.html

many (but not all yet) edits to aria live.html en and fr
new external example HTML
new French external example

mod11 aria live continuing edits

---

learning/esdc-self-paced-web-accessibility-course/module11/aria-live-fr.html
learning/esdc-self-paced-web-accessibility-course/module11/aria-live.html

extensive changes to both files

Mod11 aria-live vetted both lang

---

learning/esdc-self-paced-web-accessibility-course/module11/aria-live.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod11 sitemap update for aria live section

Mod11 sitemap for aria live

---

learning/esdc-self-paced-web-accessibility-course/module11/time-limits.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod11 sitemap timelimits and BP EN

Mod11 sitemap timelimits and BP EN

---

learning/esdc-self-paced-web-accessibility-course/module10/introduction.html
learning/esdc-self-paced-web-accessibility-course/module10/keyboard-input.html
learning/esdc-self-paced-web-accessibility-course/module10/mouse-input.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod10 sitemap update 1 includes (Mouse input and Keyboard input)

Mod10 sitemap update 1 (Mouse input and Keyboard input)

---

learning/esdc-self-paced-web-accessibility-course/module11/time-limits.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod11 sitemap update with the missing path

Mod11 sitemap update with the missing path

---

learning/esdc-self-paced-web-accessibility-course/module10/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module10/motion-actuation.html
learning/esdc-self-paced-web-accessibility-course/module10/touch-input.html
learning/esdc-self-paced-web-accessibility-course/module10/voice-input.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod10 sitemap all section of input modalities complete

Mod10 sitemap all section of input modalities complete

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod11 BP sitemap path update

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod10 sitemap list update

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod11 sitemap fixes for heading levels.

Mod11 sitemap fixes

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod10 and Mod11 minor fixes

---

learning/esdc-self-paced-web-accessibility-course/module9/animation-motion.html
learning/esdc-self-paced-web-accessibility-course/module9/captions.html
learning/esdc-self-paced-web-accessibility-course/module9/description-visual.html
learning/esdc-self-paced-web-accessibility-course/module9/flashing-content.html
learning/esdc-self-paced-web-accessibility-course/module9/pause-stop-hide.html
learning/esdc-self-paced-web-accessibility-course/module9/transcribing-audio.html
learning/esdc-self-paced-web-accessibility-course/module9/transcripts.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod9 sitemap

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-design.html
learning/esdc-self-paced-web-accessibility-course/module8/zoom.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod8 Sitemap update 1

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-design.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-forms.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-images.html
learning/esdc-self-paced-web-accessibility-course/module8/zoom.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod8-Sitemap-update2

---

learning/esdc-self-paced-web-accessibility-course/module8/orientation.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-tables.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod8 Sitemap update 3 - complete

Mod8 Sitemap update 3 - complete

---

learning/esdc-self-paced-web-accessibility-course/module11/aria-live-fr.html
learning/esdc-self-paced-web-accessibility-course/module11/aria-live.html
learning/esdc-self-paced-web-accessibility-course/module11/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module11/time-limits-fr.html
learning/esdc-self-paced-web-accessibility-course/module11/time-limits.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod11 sitemap french

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod11 sitemap FR page update

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-video.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod8 sitemap ENpage update

---

learning/esdc-self-paced-web-accessibility-course/module10/best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module10/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module10/keyboard-input-fr.html
learning/esdc-self-paced-web-accessibility-course/module10/keyboard-input.html
learning/esdc-self-paced-web-accessibility-course/module10/motion-actuation-fr.html
learning/esdc-self-paced-web-accessibility-course/module10/motion-actuation.html
learning/esdc-self-paced-web-accessibility-course/module10/mouse-input-fr.html
learning/esdc-self-paced-web-accessibility-course/module10/touch-input-fr.html
learning/esdc-self-paced-web-accessibility-course/module10/voice-input-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod10 Sitemap FR

---

learning/esdc-self-paced-web-accessibility-course/module11/time-limits-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod11 sitemap fr update

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod8 sitemap english <ul> update

Mod8 sitemap english <ul> update

---

learning/esdc-self-paced-web-accessibility-course/module6/multi-step-forms.html

added missing hidden text

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod8 deleted empty spaces

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod9 sitemap french

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod11 emptyspace removal

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod8 sitemap French

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod9 and 11 sitemap update

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod7 sitemap english

---

learning/esdc-self-paced-web-accessibility-course/module7/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module7/colour.html
learning/esdc-self-paced-web-accessibility-course/module7/contrast.html
learning/esdc-self-paced-web-accessibility-course/module7/css-generated.html
learning/esdc-self-paced-web-accessibility-course/module7/hiding-content.html
learning/esdc-self-paced-web-accessibility-course/module7/textspacing.html
learning/esdc-self-paced-web-accessibility-course/module7/visual-proximity.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod7 sitemap id fixes

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod 7 French sitemap complete

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod11 ul fixes in BP

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Mod7 FR id fixes

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Mod 8 and 9 URL fixes

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-design-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-forms-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-tables-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-video-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Mod8 FR url fixes

---

learning/esdc-self-paced-web-accessibility-course/module6/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module6/form-instructions.html
learning/esdc-self-paced-web-accessibility-course/module6/forms-concepts.html
learning/esdc-self-paced-web-accessibility-course/module6/grouping-controls.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod6 sitemap english update 1

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod6 sitemap eng update

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod 11 ul and li fixes

---

learning/esdc-self-paced-web-accessibility-course/module6/form-instructions-fr.html
learning/esdc-self-paced-web-accessibility-course/module6/grouping-controls-fr.html
learning/esdc-self-paced-web-accessibility-course/module6/multi-step-forms-fr.html
learning/esdc-self-paced-web-accessibility-course/module6/multi-step-forms.html
learning/esdc-self-paced-web-accessibility-course/module6/user-notifications-fr.html
learning/esdc-self-paced-web-accessibility-course/module9/captions-fr.html
learning/esdc-self-paced-web-accessibility-course/module9/captions.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod6 sitemap french

---

services/service-standards-en.html
services/service-standards-fr.html

Updated number of working days for a11y compliance assessments on ICT

Updated number of working days for a11y compliance assessments on ICT

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Mod6 sitemap fr indent fixed

---

learning/esdc-self-paced-web-accessibility-course/module5/functional-images.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod5 sitemap EN update 1

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Mod6 sitemap fr indent fixes

---

learning/esdc-self-paced-web-accessibility-course/module5/complex-images.html
learning/esdc-self-paced-web-accessibility-course/module5/functional-images.html
learning/esdc-self-paced-web-accessibility-course/module5/groups-images.html
learning/esdc-self-paced-web-accessibility-course/module5/image-maps.html
learning/esdc-self-paced-web-accessibility-course/module5/images-text.html
learning/esdc-self-paced-web-accessibility-course/module5/svg-images.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod5 sitemap english update 2

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Mod5 Sitemap French update1

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod5 Sitemap French update 2

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Restoring Mohammed's edits to english sitemap from #877

restored sitemap edits from pr #877

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod10 and 11 fr fixes

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Mod 9 and 8 Fr ul li changes

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Mod6 and 7 FR UL LI fixed

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Mod5 deleted empty space

---

learning/esdc-self-paced-web-accessibility-course/module6/form-instructions-fr.html
learning/esdc-self-paced-web-accessibility-course/module6/form-instructions.html
learning/esdc-self-paced-web-accessibility-course/module6/identifying-input-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/orientation-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-forms-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-tables-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-tables.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-text-fr.html

Mod6 Changes plus Mod8 Validation errors fixes

Mod6 Changes plus Mod8 Validation errors fixes

---

learning/esdc-self-paced-web-accessibility-course/module7/contrast-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/css-generated-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/textspacing-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/visual-proximity-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-text-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/zoom-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Mod7 french ids in files fixed

Mod7 french ids in files fixed

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-images-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Mod8 sitemap fr id fixes done!

Mod8 sitemap fr id fixes

---

learning/esdc-self-paced-web-accessibility-course/module9/animation-motion-fr.html
learning/esdc-self-paced-web-accessibility-course/module9/captions-fr.html
learning/esdc-self-paced-web-accessibility-course/module9/description-visual-fr.html
learning/esdc-self-paced-web-accessibility-course/module9/pause-stop-hide-fr.html
learning/esdc-self-paced-web-accessibility-course/module9/transcribing-audio-fr.html
learning/esdc-self-paced-web-accessibility-course/module9/transcripts-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Mod9 FR id fixes complete

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Mod10 Sitemap FR links fixes

---

learning/esdc-self-paced-web-accessibility-course/module5/complex-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/functional-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/groups-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/image-maps-fr.html
learning/esdc-self-paced-web-accessibility-course/module5/images-text-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Mod 5 French links fixed

---

learning/esdc-self-paced-web-accessibility-course/module6/user-notifications-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Mod 6 French minor fixes complete.

Mod 6 French minor fixes complete.

---

learning/esdc-self-paced-web-accessibility-course/module7/contrast-fr.html
learning/esdc-self-paced-web-accessibility-course/module7/hiding-content-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod7 English and French couple sitemap and pages fixes

Mod7 English and French couple sitemap and pages fixes

---

learning/esdc-self-paced-web-accessibility-course/best-practice/all-best-practice.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

best practices and sitemap heading match

best practices and sitemap heading match

---

learning/esdc-self-paced-web-accessibility-course/best-practice/all-best-practice.html

Mod5 additional text removed

---

learning/esdc-self-paced-web-accessibility-course/best-practice/all-best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/tables-concepts-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

All best prac headings match sitemap link text
Next step generates missing links in best prac

aligning sitemap-fr with all-best-practices-fr

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Reverts bati-itao/bati-itao.github.io#976
I introduced some bad entities

Revert "repairing experiement, restoring page"

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Reverts bati-itao/bati-itao.github.io#975

Revert "test encoding of sitemap-fr"

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Had to clean the French sitemap of HTML codes for special characters

sitemaps hidden topic for each Related WCAG

---

learning/esdc-self-paced-web-accessibility-course/module10/mouse-input-fr.html
learning/esdc-self-paced-web-accessibility-course/module10/mouse-input.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Mod10 trigger link id fixed

---

learning/esdc-self-paced-web-accessibility-course/module10/mouse-input-fr.html
learning/esdc-self-paced-web-accessibility-course/module10/mouse-input.html

trigger link updated in Mod 10

trigger link updated in Mod 10

---

learning/esdc-self-paced-web-accessibility-course/module7/css-generated-fr.html

Mod7 Visual CSS French page updates.

Mod7 Visual CSS French page update

---

learning/esdc-self-paced-web-accessibility-course/module4/multi-level-headers-fr.html
learning/esdc-self-paced-web-accessibility-course/module4/multi-level-headers.html

Mod4 Multi level header table fixed

Mod4 Multi level header table fixed

---

learning/esdc-self-paced-web-accessibility-course/module3/navigation.html

Mod3 Navigation link for span fixed

Mod3 Navigation link for span fix

---

learning/esdc-self-paced-web-accessibility-course/wcag/wcag-view.html
scripts/esdc-course-wcag-view.js

fix for js of filters
Jquery import was missing
code uses class not data class for selector

fix for js of filters

---

learning/awareness/articles-2021-fr.html
learning/awareness/articles-2021.html
learning/awareness/articles-2022-fr.html
learning/awareness/articles-2022.html
learning/awareness/awareness-days-fr.html
learning/awareness/awareness-days-goc-fr.html
learning/awareness/awareness-days-goc.html
learning/awareness/awareness-days.html
learning/awareness/training-fr.html
learning/awareness/training.html

Fixed redirect issue that would send user to awareness index page instead of the users current page in the proper French/English translation.

Fixed English/French redirect url on all awareness pages

---

learning/esdc-self-paced-web-accessibility-course/module1/accessibility-guidelines.html
learning/esdc-self-paced-web-accessibility-course/module1/laws-and-government-standards.html
learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities.html

Mod1 TOC updated

---

learning/esdc-self-paced-web-accessibility-course/module2/content-structure.html
learning/esdc-self-paced-web-accessibility-course/module2/headings.html
learning/esdc-self-paced-web-accessibility-course/module2/iframes.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks.html
learning/esdc-self-paced-web-accessibility-course/module2/language.html
learning/esdc-self-paced-web-accessibility-course/module2/lists.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity.html

Mod2 TOC updated

---

learning/esdc-self-paced-web-accessibility-course/module10/motion-actuation-fr.html
learning/esdc-self-paced-web-accessibility-course/module10/motion-actuation.html

Mod10 TOC on intro removed on Motion Actuation Intro section

Mod10 TOC on intro removed on Motion Actuation Intro section

---

learning/esdc-self-paced-web-accessibility-course/missing/a_02.html
learning/esdc-self-paced-web-accessibility-course/missing/a_03.html
learning/esdc-self-paced-web-accessibility-course/missing/a_04.html
learning/esdc-self-paced-web-accessibility-course/missing/best-practice-mod-5.html
learning/esdc-self-paced-web-accessibility-course/missing/captcha.html
learning/esdc-self-paced-web-accessibility-course/missing/content-structure.html
learning/esdc-self-paced-web-accessibility-course/missing/index.html
learning/esdc-self-paced-web-accessibility-course/module0/a_01.html
learning/esdc-self-paced-web-accessibility-course/module0/a_02.html
learning/esdc-self-paced-web-accessibility-course/module0/a_03.html
learning/esdc-self-paced-web-accessibility-course/module0/a_04.html
learning/esdc-self-paced-web-accessibility-course/module0/a_05.html
learning/esdc-self-paced-web-accessibility-course/module0/a_06.html
learning/esdc-self-paced-web-accessibility-course/module0/a_07.html
learning/esdc-self-paced-web-accessibility-course/module0/a_08.html
learning/esdc-self-paced-web-accessibility-course/module0/a_09.html
learning/esdc-self-paced-web-accessibility-course/module0/a_10.html
learning/esdc-self-paced-web-accessibility-course/module0/a_11.html
learning/esdc-self-paced-web-accessibility-course/module0/best-practice.html
learning/esdc-self-paced-web-accessibility-course/module0/index.html
learning/esdc-self-paced-web-accessibility-course/module0/test.html

added sensory characteristics to mod 2 Content structure, course CSS file to mod0 files

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

sitemap FR updates complete

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Reverts bati-itao/bati-itao.github.io#1055

Revert "sitemap FR updates complete"

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Mod2 and 3 sitemap FR done

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Mod4 to Mod 7 FR sitemap updated

Mod4 to Mod 7 FR sitemap updated

---

learning/esdc-self-paced-web-accessibility-course/module2/content-structure-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/headings-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/iframes-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/landmarks-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/language-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/lists-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/parsing-and-validity-fr.html
learning/esdc-self-paced-web-accessibility-course/module3/links-fr.html
learning/esdc-self-paced-web-accessibility-course/module3/navigation-fr.html

Mod 2 and 3 SC with French updated

Mod 2 and 3 SC with French updated

---

learning/document-auditor-learning-path/index-fr.html
learning/document-auditor-learning-path/index.html

Changed thead child elements on the index pages for the document auditor learning path pages:
- td to th and added the proper scope attribute.

fixed incorrect markup for all table heads

---

learning/document-auditor-learning-path/index-fr.html
learning/document-auditor-learning-path/index.html

Added bottom margin on the div container to provide additional spacing between the bottom of the table and footer.

added bottom margin on div container to provide better spacing

---

learning/esdc-self-paced-web-accessibility-course/module8/responsive-images-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/responsive-tables-fr.html
learning/esdc-self-paced-web-accessibility-course/module8/zoom.html

TOC, Header and SC fixes complete

TOC, Header and SC fixes

---

learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

Sitemap updates

---

resources/best-practices-outlook-en.html
resources/best-practices-outlook-fr.html

Added Calibri to the list of accessible fonts

Added Calibri to the list of accessible fonts

---

learning/awareness/awareness-days-fr.html
learning/awareness/awareness-days-goc-fr.html
learning/awareness/awareness-days-goc.html
learning/awareness/awareness-days.html

Updated awareness-days and awareness-days-goc content to add updated information for June and July months.

updated june/july content for awareness-days pages

---

learning/newsolutionrequest.html

PowerAppFile html added

---

resources/faq-web-accessibility-en.html
resources/faq-web-accessibility-fr.html

Added files for FAQ - Web Accessibility page.
Can be found at:
/resources/faq-web-accessibility-en.html
/resources/faq-web-accessibility-fr.html

added the faq web accessibility files

---

learning/esdc-self-paced-web-accessibility-course/test-folder/nvdatestfile.html

Changes to NVDA test file with latest WET Style

Changes to NVDA test file with latest WET Style

---

learning/esdc-self-paced-web-accessibility-course/test-folder/formcheck.css
learning/esdc-self-paced-web-accessibility-course/test-folder/nvdacheck3.css

CSS Files are added

---

resources/bookmarks-fr.html
resources/bookmarks.html

Added guide for hosting virtual meetings (DAT) to useful links

Added hosting virtual meetings guide to useful links

---

learning/esdc-self-paced-web-accessibility-course/test-folder/nvdatestfile-old.html
learning/esdc-self-paced-web-accessibility-course/test-folder/nvdatestfile.html

Updated Sol Req form with error message check

Updated Sol Req form with error message

---

learning/esdc-self-paced-web-accessibility-course/test-folder/nvdatest4.css

An updated CSS added to support the new changes

An updated CSS added

---

learning/esdc-self-paced-web-accessibility-course/test-folder/nvdatest4.css
learning/esdc-self-paced-web-accessibility-course/test-folder/nvdatestfile.html

More test done on NVDA to check error message and some tweaks

More test done on NVDA to check error message

---

learning/esdc-self-paced-web-accessibility-course/test-folder/nvdatestfile.html

Minor typo in the form corrected

Minor typo in the form corrected

---

learning/coaches/assessment/a11y-6636-2022-06-30-PowerApps/nvdatest4.css
learning/coaches/assessment/a11y-6636-2022-06-30-PowerApps/nvdatestfile.html

New folders under Coaches created and files added

New folders under Coaches created and files added

---

learning/coaches/assessment/a11y-6636-2022-06-30-PowerApps/nvdatestfile.html

Added a dynamic text box to the toggle button

Added a dynamic text box to the toggle button

---

learning/document-auditor-learning-path/document-auditor-learning-path-en.html
learning/document-auditor-learning-path/document-auditor-learning-path.json
scripts/learningpath.js

-Converted the Document Auditor Learning path into JSON
-Add learningpath.js script which dynamically adds the JSON data to the new document-auditor-learning-path-en.html page.

converted document auditor learning path to JSON and added script

---

resources/bookmarks-fr.html
resources/bookmarks.html

Added a few links from the old WS CoE site to bookmarks.

added WS CoE content to useful links

---

learning/document-auditor-learning-path/document-auditor-learning-path-fr.html
learning/document-auditor-learning-path/document-auditor-learning-path.json

Added the French for the the document auditor learning path json file and created the french html page.

Add json french document learning path

---

learning/document-auditor-learning-path/index-fr.html

Changed the appFooter and the wet template script from English to French.

changed scripts to french versions

---

resources/index-fr.html
resources/index.html

Added a link and paragraph block on resources/index for the accessible-image html page

added link and parapgraph on resource index for accessible-images

---

learning/learning-path-for-auditors/web-auditor-learning-path/web-auditor-learning-path-en.html
learning/learning-path-for-auditors/web-auditor-learning-path/web-auditor-learning-path-fr.html
learning/learning-path-for-auditors/web-auditor-learning-path/web-auditor-learning-path.json
scripts/learningpath.js

-Restructured file structure to better organize the learning path section
-Added json file, and html files for the web auditor learning path
-Updated learningpath.js script to dynamically check for the correct json fiel.
-Completed all blocks (A-E) for the web auditor learning path json file.

Add web auditor learning path json

---

learning/learning-path-for-auditors/web-auditor-learning-path/web-auditor-learning-path-en.html
learning/learning-path-for-auditors/web-auditor-learning-path/web-auditor-learning-path-fr.html

Added additional breadcrumb links to the web auditor learning path html pages.

added breadcrumbs for web auditor pages

---

learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities-fr.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap-fr.html

on Types of disabilities and Sitemap pages
added "audio" to "audio-video"

replaced Deaf with Auditory disability in French

---

learning/esdc-self-paced-web-accessibility-course/module1/types-of-disabilities.html
learning/esdc-self-paced-web-accessibility-course/sitemap/sitemap.html

Changed from Deaf to Auditory Disability in Mod 1 and Sitemap

Changed from Deaf to Auditory Disability

---

teams/svatic-ictaas/index-fr.html

- Changed the `appFooter.min.js` script to `appFooter-fr.min.js`

changed appFooter script to French version

---

ajax/menu-en.html
ajax/menu-fr.html

- Added Learning Path for Auditors to the Learning dropdown menu.
- Added Accessible Images to the Resources + Tools dropdown menu.

Add menu items

---

ajax/menu-fr.html

- Added the Projects and Partners link back into the French version of the navigation menu.

added projects and partners link to french menu

---

projects/index-fr.html
projects/index.html

- Removed the work in progress div from partners page

removed work in progress from partners page

---

learning/awareness/articles-2022-fr.html
learning/awareness/articles-2022.html
learning/awareness/awareness-days-fr.html
learning/awareness/awareness-days-goc-fr.html
learning/awareness/awareness-days-goc.html
learning/awareness/awareness-days.html
learning/awareness/awareness-event-fr.html
learning/awareness/awareness-event.html

Added Awareness updates to the following pages:
- Awareness Days & Awareness Days GoC
- Awareness Events 2022
- Articles 2022

Add awareness updates

---

learning/esdc-self-paced-web-accessibility-course/best-practice/all-best-practice-fr.html
learning/esdc-self-paced-web-accessibility-course/best-practice/all-best-practice.html

added disabled button state to All Best Practices

---

learning/awareness/awareness-days-fr.html
learning/awareness/awareness-days.html

Added new updates to the awareness-days pages

Updated awareness-days pages

---

services/service-standards-en.html
services/service-standards-fr.html

Updated loan time from 7 to 14 days on the `service-standards-en` and `service-standards-fr` pages

updated loan time from 7 to 14 days

---

learning/awareness/articles-2021-fr.html
learning/awareness/articles-2021.html
learning/awareness/articles-2022-fr.html
learning/awareness/articles-2022.html
learning/awareness/awareness-days-fr.html
learning/awareness/awareness-days-goc-fr.html
learning/awareness/awareness-days-goc.html
learning/awareness/awareness-days.html
learning/awareness/awareness-event-fr.html
learning/awareness/awareness-event.html
learning/awareness/index-fr.html
learning/awareness/index.html
learning/awareness/training-fr.html
learning/awareness/training.html

Added missing h2 to the side nav bar to fix the skipped heading level warning.

added missing heading level for side nav bar

---

dashboard/index-fr.html
dashboard/index.html

fixed the path to the index pages listed on the monthly dashboard.

updated index links on dashboard page

---

learning/awareness/awareness-days-fr.html
learning/awareness/awareness-days.html

Removed empty a tags from the awareness days pages.

removed empty a tags from awareness days pages

---

learning/coaches/demo-site/css/demo.css
learning/coaches/demo-site/home.html

moved nav our of banner
removed padding and margins from elements with flex percentage widths

moved nav out of banner

---

dashboard/index-fr.html
dashboard/index.html

Added bar graph to represent monthly request data on the dashboard.

added WET bar graph for monthly requests

---

ajax/menu-en.html
ajax/menu-fr.html
learning/index-fr.html
learning/index.html

Added links for the awareness section on the learning page and ajax menu.

added links for awareness section

---

learning/awareness/index.html

Fixed the closure script to use the `wet-en` version instead of `wet-fr`

changed wet closure script from fr to en

---

learning/awareness/index-fr.html
learning/awareness/index.html

Removed  `<br>` tags that were being used for line breaks and converted the content into lists with css margin.

Remove br awareness

---

learning/awareness/index-fr.html
learning/awareness/index.html

Removed two stray `<td>` tags from the awareness table on French and English index pages.

Fix table data cell awareness

---

learning/awareness/articles-2021-fr.html
learning/awareness/articles-2021.html
learning/awareness/articles-2022-fr.html
learning/awareness/articles-2022.html
learning/awareness/awareness-days-fr.html
learning/awareness/awareness-days-goc-fr.html
learning/awareness/awareness-days-goc.html
learning/awareness/awareness-days.html
learning/awareness/awareness-event-fr.html
learning/awareness/awareness-event.html
learning/awareness/training-fr.html
learning/awareness/training.html

Added missing table scope to all tables on awareness pages.

Add scope to awareness tables

---

learning/esdc-self-paced-web-accessibility-course/module6/multi-step-forms-fr.html
learning/esdc-self-paced-web-accessibility-course/module6/multi-step-forms.html

- mod 6 - multi-steps-forms - added internal links to TOC and best practice
- updated english and french pages

mod 6 - multi-steps-forms - added internal links

---

awareness/articles-2021-fr.html
awareness/articles-2021.html
awareness/articles-2022-fr.html
awareness/articles-2022.html
awareness/awareness-days-fr.html
awareness/awareness-days-goc-fr.html
awareness/awareness-days-goc.html
awareness/awareness-days.html
awareness/awareness-event-fr.html
awareness/awareness-event.html
awareness/index-fr.html
awareness/index.html
awareness/training-fr.html
awareness/training.html

Updated the breadcrumb links for all of the awareness pages

updated breadcrumb links for awareness pages

---

dashboard/index-fr.html
dashboard/index.html

Updated the monthly dashboard with content from October 2022.

Updated dashboard with October 2022 content

---

dashboard/index-fr.html
dashboard/index.html

Fixed typo on the monthly dashboard page.

fixed typo on the monthly dashboard

---

dashboard/index-fr.html
dashboard/index.html

Moved the request resolved data from a bar chart to pie chart.

added pie chart for requests resolved

---

resources/CART-services-Sign-Language-Interpreters-fr.html

removed duplicate bullet items

---

learning/esdc-self-paced-web-accessibility-course/search/search.js
learning/esdc-self-paced-web-accessibility-course/search/search_form.html
learning/esdc-self-paced-web-accessibility-course/search/searchmenu.js

changes to search page

---

teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

-Removed Roch profile
-Updated Nicolas, Fredy, and Olga profiles
-Addded Manuel and Michaela profiles

Update teams profiles

---

learning/coaches/demo-site/faq-fr.html
learning/coaches/demo-site/submit-ticket-fr.html
learning/coaches/demo-site/submit-ticket.html

French pages added to the demo site - 
submit-ticket-fr.html
faq-fr.html

French pages added to the demo site

---

learning/esdc-self-paced-web-accessibility-course/search/search.js
learning/esdc-self-paced-web-accessibility-course/search/search_form.html

The search form uses role="form". It should use role="search".
The form's aria-label is "Search site". It should be "Search course".
Missing "clear search" button
Searching for terms with hyphens doesn't work (compare aria-label with label)

some changes to search

---

learning/coaches/demo-site/submit-ticket-fr.html

French page update 2

---

awareness/awareness-event-fr.html
awareness/awareness-event.html
awareness/training-fr.html
awareness/training.html

- Updated events and training pages in both English and French

Nov awareness update

---

awareness/awareness-days-fr.html
awareness/awareness-days.html

Updated awareness-days pages in both English and French.

Update awareness days

---

dashboard/index-fr.html
dashboard/index.html

Updated the monthly dashboard with the most up-to-date data (November).

completed November update for the CIO dashboard

---

teams/styles/custom.css
teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

Removed emails for each profile on the team pages in both French and English

Update teams page

---

learning/coaches/demo-site/submit-ticket-fr.html
learning/coaches/demo-site/submit-ticket-skip-fr.html
scripts/skipto-fr.js

Added French labels to javascript and HTML. Removed region landmarks from French.

demo site js translation

---

awareness/articles-2022-fr.html
awareness/articles-2022.html

Mise à jour de la page article 2022 FR et AN.

updated articles 2022

---

resources/faq-web-accessibility-en.html
resources/faq-web-accessibility-fr.html

Used details and summary elements on FAQ page

Used details and summary elements on FAQ page

---

resources/sign-language-view-microsoft-teams-en.html
resources/sign-language-view-microsoft-teams-fr.html

Added sign language view in MS Teams pages

Added sign language view in MS Teams pages

---

resources/sign-language-view-microsoft-teams-fr.html

Updated H1 content on French sign langue=age view MS Teams

Updated H1 content on French sign langue=age view MS Teams

---

resources/sign-language-view-microsoft-teams-en.html
resources/virtual-meeting-platforms-accessibility-features-en.html
resources/virtual-meeting-platforms-accessibility-features-fr.html

-Added Sign Language View for Microsoft Teams pages to Virtual Meeting Platforms and Accessibility Features
-Updated title content on Added Sign Language View for Microsoft Teams  English page

Sign language

---

learning/coaches/assessment/AEM/alerts.html

Proposed markup for WET alerts, both static and JS live regions. This is not the best-supported JS technique.

WET alerts test file

---

learning/coaches/assessment/AEM/alerts2.html

A demo and test results of the more reliable aria live JS injection technique

demo live alerts using injected content

---

learning/coaches/assessment/AEM/alerts2.html
learning/coaches/assessment/AEM/alerts3.html

Also cleaned up the headings and the title element in each file

third test case using hidden attribute

---

learning/coaches/assessment/AEM/alerts-static.html
learning/coaches/assessment/AEM/alerts.html
learning/coaches/assessment/AEM/alerts2.html
learning/coaches/assessment/AEM/alerts3.html

Added tests for role="status" and aria-roledescription
Still need to test in JAWS

new tests for js injection

---

teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

Updated team page

---

learning/coaches/assessment/AEM/alerts2.html

Added tests three and four, three browsers each

More JAWS test results for JavaScript injection

---

learning/coaches/assessment/AEM/alerts.html

The version numbers still need to be added.

Added VoiceOver + Safari test results

---

learning/curriculum/index-fr.html
learning/curriculum/index.html

Changed CS to IT on curriculum index page.

Changed CS to IT on curriculum index page

---

resources/examples/index-fr.html
resources/examples/index.html
resources/examples/texthighlight-en.html
resources/examples/texthighlight-fr.html

Added a subfolder examples to resources.

Added a subfolder examples to resources.

---

resources/examples/texthighlight-en.html
resources/examples/texthighlight-fr.html

Updated text highlight examples.

Updated text highlight examples.

---

resources/examples/texthighlight-fr.html

Updated texthighlight-fr.html title.

Updated texthighlight-fr.html title

---

resources/examples/texthighlight-fr.html

Updated  H1 on texthighlight-fr.html

Updated  H1 on texthighlight-fr.html

---

resources/accessible-software-en.html
resources/accessible-software-fr.html

Removed non-web checklist form accessible software page.

Removed non-web checklist form accessible software page.

---

teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

Added Kellyanne and Michelle to the team page.

Added Kellyanne and Michelle to the team page

---

teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

Updated the team page

---

teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

Updated team page content

---

learning/esdc-self-paced-web-accessibility-course/module9/best-practice-mod-9.html

Typo corrected under BP Audio Control

Typo corrected under BP Audio Control

---

resources/faq-web-accessibility-en.html
teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

Added Rabab to the team page

---

learning/coaches/demos/node-semantics-example-aria.html

Deepened button contrast - Semantics demo

---

awareness/upcoming-events-fr.html

Replaced è by é in évènement

---

awareness/upcoming-events.html

Added a missing paragraph to upcoming-events.html

Added a missing paragraph to upcoming-events.html

---

awareness/awareness-event-fr.html
awareness/awareness-event.html
awareness/index-fr.html
awareness/index.html
awareness/upcoming-events-fr.html
awareness/upcoming-events.html

Updated events pages

---

awareness/archived-training-fr.html
awareness/archived-training.html
awareness/training-fr.html
awareness/training.html
awareness/upcoming-events-fr.html
awareness/upcoming-events.html

Updated awareness section content.

Updated awareness section content

---

awareness/archived-training.html
awareness/articles-2021-fr.html
awareness/articles-2021.html
awareness/articles-2022-fr.html
awareness/articles-2022.html
awareness/index-fr.html
awareness/index.html
awareness/training-fr.html
awareness/training.html
awareness/upcoming-events-fr.html
awareness/upcoming-events.html

Updated the awareness section.

Updated the awareness section

---

teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

Familiarizing myself with the process. Added a tag line for Manuel EN/FR. Verified content with Live Server.

Small updates to svatic-ictaas

---

awareness/articles/Developmental-Disabilities-Awareness-Month-fr.html
awareness/articles/Developmental-Disabilities-Awareness-Month.html
awareness/articles/World-Autism-Awareness-Day-fr.html
awareness/articles/World-Autism-Awareness-Day.html
awareness/articles/World-Braille-Day-fr.html
awareness/articles/World-Braille-Day.html
awareness/articles/World-Cancer-Day-fr.html
awareness/articles/World-Cancer-Day.html

note that I didn't update the breadcrumbs as I am not sure from where this is going to be available from. My objective with this pull request is to get familiar with the process and getting the rust off my skills.

trying to upload my changes for approval

---

teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

Updating the Team names on svatic-ictaas page. FR and EN.

Updating the Team names on svatic-ictaas page

---

teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

Moved members of the ITAO to their proper teams. EN and FR. Gave it a quick check with Live Server.

Moved members of the ITAO to their proper teams.

---

teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

Reverts bati-itao/bati-itao.github.io#1368

Revert "Moved members of the ITAO to their proper teams."

---

teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

Reverts bati-itao/bati-itao.github.io#1370

Revert "Revert "Moved members of the ITAO to their proper teams.""

---

teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

Moved Richa and Liban to ASAC/SASC.

Moved Richa and Liban to ASAC/SASC.

---

awareness/articles/rsi-awareness-day-fr.html
awareness/articles/rsi-awareness-day.html

added 2 pages, one for the RSI article in French, the other for the RSI article in English

Creation of RSI awareness day article

---

awareness/training-fr.html
awareness/training.html

Remove expand/collapse from training pages

Remove expand/collapse from training pages

---

teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

This should fix most of the outstanding issues with the page. Lots of changes to both the English and the French page. If there are any problems, please let me know.

ITAO Team Page Fix

---

teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

Moving Kellyanne Lecuyer back to ACE

Moving Kellyanne Lecuyer back to ACE

---

teams/svatic-ictaas/index-en.html
teams/svatic-ictaas/index-fr.html

ITAO Team Page updates.

---

services/service-standards-en.html
services/service-standards-fr.html

Aug 2 service standard updates to three service titles.

ITAO Service Standard Updates

---

resources/faq-web-accessibility-en.html

English page updated up to "Is a splash page required for my application".

FAQ Web Accessibility Updates

---

services/service-standards-en.html
services/service-standards-fr.html

Management wants the previous service delivery values restored.

restore previous service delivery values

---

awareness/articles/national-service-dog-month-fr.html
awareness/articles/national-service-dog-month.html

created National Service Dog Month pages

---

awareness/articles/national-service-dog-month-fr.html
awareness/articles/national-service-dog-month.html

remove bullet point on when the dogs were introduced

made a change as requested

---

awareness/articles/national-service-dog-month-fr.html
awareness/articles/national-service-dog-month.html
awareness/upcoming-events-fr.html
awareness/upcoming-events.html

changes made as requested:
Changement à apporter sur ces pages :
Mois National des Chiens d'Assistance
National Service Dog Month
1.	Nouvelle date : mercredi 13 septembre au lieu de mercredi 20 septembre
2.	Nouveau lien SABA
En même temps, si possible, pourrais-tu svp apporter ces petites changements :
Sur cette page : Événements à venir- Sensibilisation à l'accessibilité
1.	Ajouter lettre majuscule au titre – Événements à Venir
2.	Titre de l’événement un peu plus gros s.v.p
3.	Ajouter lettre majuscule au titre – Événements Passés
Sur cette page : Upcoming events - Accessibility Awareness
1.	Ajouter lettre majuscule au titre – Upcoming Events
2.	Titre de l’événement un peu plus gros s.v.p
3.	Ajouter lettre majuscule au titre – Past Events

changes on upcoming events and September article

---

resources/faq-web-accessibility-en.html
resources/faq-web-accessibility-fr.html

including Heading 1 (H1)... which usually is the page title. EN & FR.

Small update to FAQ

---

resources/faq-web-accessibility-en.html
resources/faq-web-accessibility-fr.html

Added internal link notice and icon to FAQ pages

Added internal link notice and icon to FAQ pages

---

resources/accessible-web-pages-en.html
resources/accessible-web-pages-fr.html

Add FAQ page to accessible web pages

Add FAQ page to accessible web pages

---

resources/pdf-accessibility-checklist-en.html
resources/pdf-accessibility-checklist-fr.html

replacing Foxit phantom PDF with Foxit PDF Editor

PDF accessibility checklist updates

---

resources/pdf-accessibility-checklist-fr.html

Small update to French PDF accessibility checklist

Small update to French PDF accessibility checklist

---

resources/microsoft-forms-polls-best-practices-fr.html
resources/microsoft-forms-polls-best-practices.html

Quick fix requested by Larry. French and English.

Fixing IFFS link

---

teams/svatic-ictaas/index-en.html

Remove Fredy from Our Team EN

---

teams/svatic-ictaas/index-en.html

Added Nicolas back as manager.

Fixing EN side

---

resources/ms-doc-compliance-checklist-en.html
resources/ms-doc-compliance-checklist-fr.html

Updating EN and FR to point to Microsoft 365 information instead of Office 2016.

MSComplianceChecklist update

---

resources/pdf-accessibility-checklist-en.html
resources/pdf-accessibility-checklist-fr.html

PDF Accessibility Checklist update

---

resources/pdf-accessibility-checklist-en.html
resources/pdf-accessibility-checklist-fr.html

Linking to Anne's updated documentation. EN & FR.

PDF Accessibility changing links

---

resources/ms-doc-compliance-checklist-en.html
resources/ms-doc-compliance-checklist-fr.html

Updating links and some content on the FR and EN pages.

Microsoft Document Compliance Checklist updates

---

awareness/upcoming-events-fr.html
awareness/upcoming-events.html

Awareness Upcoming Events update EN & FR for Feb 22.

Awareness Upcoming Events update

---

awareness/upcoming-events-fr.html
awareness/upcoming-events.html

Small fix, removed reference to an accessibility 101 training at the end of the session.

Upcoming Event Fix

---

awareness/articles/reconciliation-in-action.html

Fixing a link in reconciliation article

---

awareness/articles-2024-fr.html
awareness/articles-2024.html
awareness/articles/start-with-accessibility-fr.html
awareness/articles/start-with-accessibility.html
awareness/articles/world-cancer-day-2024-fr.html
awareness/articles/world-cancer-day-2024.html
awareness/past-events-fr.html
awareness/past-events.html

Posting 2 articles and updating the associated pages. Also updating the past event page to include the new link

Posting of article pages

---

awareness/past-events-fr.html
awareness/past-events.html
awareness/training-fr.html
awareness/training.html
awareness/upcoming-events-fr.html
awareness/upcoming-events.html

Updated the Upcoming event page to have the April event, Updated the training page to include the April events. Updated the past Event page to include the 2nd February presentation and the March presentation.

update to awareness pages

---

awareness/training-fr.html
learning/esdc-self-paced-web-accessibility-course/module2/language.html

self paced course and awareness update

self paced course and awareness update

---

resources/accessible-documents-questions-answers-fr.html
resources/accessible-documents-questions-answers.html

Remove reference to document accessibility training recordings.

Remove reference to recordings

---

resources/introduction-accessibility-en.html
resources/introduction-accessibility-fr.html

Update Microsoft 365 wiki link English and French

Update Microsoft 365 wiki link

---

awareness/archived-training-fr.html
awareness/archived-training.html
learning/learning-path-for-auditors/document-auditor-learning-path/document-auditor-learning-path.json
learning/learning-path-for-auditors/document-auditor-learning-path/index-fr.html
learning/learning-path-for-auditors/document-auditor-learning-path/index.html
resources/accessible-documents-questions-answers-fr.html
resources/accessible-documents-questions-answers.html

Replacing Microsoft Office 2016 with 365 site wide

Replacing Microsoft Office 2016 with 365 site wide

---

awareness/articles/accessibility-tools-and-adaptive-technology-for-deaf.html
awareness/articles/accessibility-tools-and-adaptive-technology-for-neurodiverse-employees.html
awareness/articles/world-sight-day.html
resources/pdf-accessibility-checklist-en.html

Updating RMT link site wide.

---

awareness/training-fr.html
awareness/training.html

Update Training and Coaching for May

Update Training and Coaching for May

---

awareness/training-fr.html
awareness/training.html

Awareness May Training Fixes and Updates

Awareness May Training Fixes and Updates

---

awareness/past-events-fr.html
awareness/past-events.html

Updated past awareness events for April 2024

Updated past awareness events for April 2024

---

awareness/articles-2024-fr.html
awareness/articles-2024.html
awareness/articles/accessibility-awareness-day-2024-fr.html
awareness/articles/accessibility-awareness-day-2024.html

Adding Accessibility Awareness Day Pages May 2024 English and French.

Adding Accessibility Awareness Day Pages May 2024 EN and FR.

---

awareness/upcoming-events-fr.html
awareness/upcoming-events.html

Updates to May Upcoming Events. FR and EN.

Updates to May Upcoming Events

---

awareness/upcoming-events-fr.html

Minor awareness update

---

awareness/upcoming-events.html

Minor correction to Awareness Event. English.

Minor correction to Awareness Event. English.

---

awareness/articles-2024-fr.html
awareness/articles-2024.html
awareness/articles/accessible-and-inclusive-meetings-2024-fr.html
awareness/articles/accessible-and-inclusive-meetings-2024.html

Adding Accessible Meetings article 2024 EN and FR.

Adding Accessible Meetings article 2024 EN and FR.

---

awareness/articles-2024-fr.html
awareness/articles-2024.html
awareness/articles/accessibility-awareness-day-2024-fr.html
awareness/articles/accessibility-awareness-day-2024.html
awareness/articles/accessible-and-inclusive-meetings-2024-fr.html
awareness/articles/accessible-and-inclusive-meetings-2024.html
awareness/articles/national-AccessAbility-week-2024-fr.html
awareness/articles/national-AccessAbility-week-2024.html
awareness/articles/reconciliation-in-action-fr.html
awareness/articles/reconciliation-in-action.html
awareness/articles/start-with-accessibility-fr.html
awareness/articles/start-with-accessibility.html
awareness/articles/understanding-neurodiversity-fr.html
awareness/articles/understanding-neurodiversity.html
awareness/articles/world-cancer-day-2024-fr.html
awareness/articles/world-cancer-day-2024.html

Added a new article and updated the content menu to contain "Articles from 2024". 16 changed files total.

Lots of updates to Accessibility Awareness EN and FR.

---

awareness/articles/accessible-and-inclusive-meetings-2024-fr.html
awareness/articles/functional-neurological-disorder-awareness-month-2024-fr.html
awareness/articles/national-AccessAbility-week-2024-fr.html

Minor changes to fix FR top menu and breadcrumbs, in three recent files.

Minor changes to fix FR top menu and breadcrumbs.

---

resources/CART-services-Sign-Language-Interpreters-en.html
resources/CART-services-Sign-Language-Interpreters-fr.html

replacing SLIAO with Asign. EN & FR.

Updating CART services SLI page to include asign.

---

resources/CART-services-Sign-Language-Interpreters-en.html
resources/CART-services-Sign-Language-Interpreters-fr.html

Small corrections to CART services update. EN and FR.

---

awareness/training.html

English Training and Coaching update June 2024

English Training and Coaching update June 2024

---

awareness/past-events-fr.html
awareness/past-events.html

Past event updates for May 2024

Past event updates for May 2024

---

resources/Official-languages-recommendations-en.html
resources/Official-languages-recommendations-fr.html

OL recommendations 404 links fix. EN and FR.

OL recommendations 404 links fix. EN and FR.

---

awareness/articles/reveal-or-conceal-disclosing-disability-2024-fr.html
awareness/articles/reveal-or-conceal-disclosing-disability-2024.html
awareness/past-events-fr.html
awareness/past-events.html

Added a new article "Reveal or Conceal: The Pros and Cons of Disclosing a Disability in the Workplace".
Updated the past articles with the recording of "My lived experience as a person born with Spina Bifida & Hydrocephalus".
English and French

May 2024 Awareness updates. EN and FR.

---

awareness/articles-2024-fr.html
awareness/articles-2024.html

Updating: https://bati-itao.github.io/awareness/articles-2024.html, https://bati-itao.github.io/awareness/articles-2024-fr.html

Updating articles page with new article

---

awareness/articles-2024-fr.html
awareness/articles-2024.html
awareness/articles/intro-to-WCAG-2024-fr.html
awareness/articles/intro-to-WCAG-2024.html

add awareness article for WCAG 2.1

add awareness article for WCAG 2.1

---

awareness/articles/intro-to-WCAG-2024-fr.html
awareness/articles/intro-to-WCAG-2024.html

awareness WCAG article update to POUR link

awareness WCAG article update to POUR link

---

awareness/training-fr.html
awareness/training.html

training.html and training-fr.html updates for July 2024

training.html and training-fr.html updates for July 2024

---

awareness/training-fr.html
awareness/training.html

Training page update EN and FR

Training page update EN and FR

---

awareness/training-fr.html
awareness/training.html

April French Accessibility Training Cancelled Update

April French Accessibility Training Cancelled Update
