resources/accessible-web-pages-en.html, resources/accessible-web-pages-fr.html
- Removed Section 508 link
- Fixed “Canadian Standards on Web Accessibility” and “European Standards – EN 301 549” are on the same line
- Updated “Web Accessibility Checklist” to “Web accessibility checklist for ESDC development teams”
=> Removed section 508 link

learning/esdc-self-paced-web-accessibility-course/content-structure.html, learning/esdc-self-paced-web-accessibility-course/headings.html, learning/esdc-self-paced-web-accessibility-course/landmarks.html, learning/esdc-self-paced-web-accessibility-course/language.html, learning/esdc-self-paced-web-accessibility-course/lists.html, learning/esdc-self-paced-web-accessibility-course/parsing-and-validity.html
**landmarks.html**
- Added "Good" to example title and WET class
- Added codeblock markup
- Added highlight.js  in the head
**headings.html**
- Added "Good" to example title and WET class
- Added codeblock markup
- Added highlight.js  in the head
**content-structure.html**
- Replaced class=â€language-htmlâ€ with class="language-html" on code blocks
- Removed the inconsistently-applied heading "Code Snippet" (Mohammed is adding visually-hidden messages)
- Added "Good" example and class
- Added quote markup to two examples
**language.html**
- Demoted the heading "Related WCG resources", removed it's parent <section>, moved it into the previous section, removed from TOC
**parsing-and-validity.html**
- Added "Good" and "Bad" example WET classes
=> example headings and code blocks

learning/esdc-self-paced-web-accessibility-course/module2/language.html
In language.html, fixed the path to the CSS and set a heading in sentence case.
=> path to syntax highlighter CSS

learning/esdc-self-paced-web-accessibility-course/module2/landmarks.html
In Mod 2 common landmark example the code has been indented.
=> code indent done on the example code

learning/esdc-self-paced-web-accessibility-course/module2/landmarks.html
Double spacing on the code example in Landmark is fixed.
=> Landmark indent double space fixed

learning/esdc-self-paced-web-accessibility-course/module2/landmarks.html
From "Follow these best practices for page regions and landmarks"
To "Best practices for page regions and landmarks"
=> Shortened long heading

teams/svatic-ictaas/index-en.html, teams/svatic-ictaas/index-fr.html
Remarks:
Text overflow for Titus Cristea;
Some squares for each person are longer/shorter;
Some icons are now purple or black instead of dark blue;
ACE team have 1 row that is different than the rest;
In FR, I don't know how to translate: Loan to iService, Sr Advisor, Infrastructure/Ops, and Product management. (I never received an FR document for the team page, so maybe other translations that are weird)
=> Team page update en-fr

learning/document-auditor-learning-path/index-fr.html, learning/document-auditor-learning-path/index.html
Added the correct property and id value to the H1 on the index pages to fix the skip link.
=> fixed broken skip links for document auditor index pages

learning/document-auditor-learning-path/index-fr.html, learning/document-auditor-learning-path/index.html
Updated the titles on the document auditor index pages to match the h1 elements and provide a more detailed description.
=> updated titles on document auditor index pages to match h1's

learning/esdc-self-paced-web-accessibility-course/module10/introduction-fr.html, learning/esdc-self-paced-web-accessibility-course/module10/motion-actuation-fr.html, learning/esdc-self-paced-web-accessibility-course/module10/mouse-input-fr.html, learning/esdc-self-paced-web-accessibility-course/module10/touch-input-fr.html, learning/esdc-self-paced-web-accessibility-course/module3/navigation-fr.html, learning/esdc-self-paced-web-accessibility-course/module6/forms-concepts-fr.html, learning/esdc-self-paced-web-accessibility-course/module7/colour-fr.html, learning/esdc-self-paced-web-accessibility-course/module7/contrast-fr.html, learning/esdc-self-paced-web-accessibility-course/module7/hiding-content-fr.html, learning/esdc-self-paced-web-accessibility-course/module7/introduction-fr.html, learning/esdc-self-paced-web-accessibility-course/module7/textspacing-fr.html, learning/esdc-self-paced-web-accessibility-course/module8/introduction-fr.html, learning/esdc-self-paced-web-accessibility-course/module8/responsive-design-fr.html, learning/esdc-self-paced-web-accessibility-course/module8/responsive-images-fr.html, learning/esdc-self-paced-web-accessibility-course/module8/zoom-fr.html, learning/esdc-self-paced-web-accessibility-course/module9/animation-motion-fr.html, learning/esdc-self-paced-web-accessibility-course/wcag/wcag-view-fr.html
Updated our 2.1 translations with official translations
Updated the WCAG resources of three intro pages (mods 7, 8, 10) and three standalone links that had English WCAG link text, 
Deleted 2 instances of En anglais seulement paragraphs
=> Official wcag 2.1 SC translations

scripts/learningpath.js
Updated learningpath.js script to:
- Only include format options in the html if the `?format=` search param is included in the URL.
- Changed all `title.includes(string)` occurrences to `title.indexOf(string) !== -1` as `.includes()` is not supported on IE.
=> script only shows format options if in search params & added IE fix

learning/learning-path-for-auditors/index-fr.html, learning/learning-path-for-auditors/index.html
Updated links and paragraph text on  `/learning-path-for-auditors/index` pages to include the following html files that are using JSON data:
- `document-auditor-learning-path/document-auditor-learning-path-en.html`
- `document-auditor-learning-path/document-auditor-learning-path-fr.html`
- `/web-auditor-learning-path/web-auditor-learning-path-en.html`
- `/web-auditor-learning-path/web-auditor-learning-path-fr.html`
=> updated links and paragraph text for auditor learning path indexs

learning/learning-path-for-auditors/document-auditor-learning-path/document-auditor-learning-path-en.html, learning/learning-path-for-auditors/document-auditor-learning-path/document-auditor-learning-path-fr.html, learning/learning-path-for-auditors/index-fr.html, learning/learning-path-for-auditors/index.html
Updated breadcrumb links for:
- `/learning-path-for-auditor/index.html`
- `/learning-path-for-auditor/index-fr.html`
- `/document-auditor-learning-path/document-auditor-learning-path-en.html`
- `/document-auditor-learning-path/document-auditor-learning-path-fr.html`
=> Add missing breadcrumbs

learning/learning-path-for-auditors/document-auditor-learning-path/document-auditor-learning-path.json
In Block B, Item 4:
- Fixed broken link by changing path to `./MSDocument_Audit_Report_EN.docx` & `./MSDocument_Audit_Report_FR.docx`
=> fixed broken MS_Document_Audit_Report link by changing path

scripts/bati-itao.min.js, teams/svatic-ictaas/index-en.html, teams/svatic-ictaas/index-fr.html
- Removed the temporary font awesome icon cdn library `<link>` tags from team page
- Added a new temporary icon fix to the bati-itao.min.js script to create a new `<link>` for the font awesome cdn on all pages
- This is still a temporary fix for the icons disappearing.
=> moved temporary icon fix to bati-itao.min script

learning/esdc-self-paced-web-accessibility-course/module12/apg-wet-inventory.html
Several URLs were local and needed the rest of the path.
Renamed "WAI examples" to "APG examples"
=> fixed APG links with full URL

learning/awareness/training-fr.html, learning/awareness/training.html
Removed placeholders and empty `<a>`  tags from the training pages (English and French)
=> removed placeholders and empty a tags

learning/awareness/index.html
Fixed the breadcrumb for the home link to properly redirect back to the ITAO index page.
=> fixed breadcrumb path to redirect back to home

awareness/awareness-event-fr.html, awareness/training-fr.html
Added missing info alerts messages for external link usage. Added to `awareness-events-fr.html` & `training-fr.html`
=> added missing info alerts for external link on  events + training (fr)

learning/learning-path-for-auditors/web-auditor-learning-path/web-auditor-learning-path.json
Fixed #1261 
-Removed T716 course as it is no longer available
-Updated path for ICT Web Accessibility Course with proper SABA link
=> fixed #1261 broken link

awareness/archived-articles-fr.html, awareness/archived-articles.html, awareness/articles-2024-fr.html, awareness/articles-2024.html, awareness/articles/reconciliation-in-action-fr.html, awareness/articles/reconciliation-in-action.html, awareness/index-fr.html, awareness/index.html, awareness/past-articles.html
Here is a list of the elements that I changed [All change did in both languages]:
Added page: articles-2024.html
Added page: reconciliation-in-action.html
Modified index.html: changed the link to the new 2024 article page
Modified archived-articles.html: changed the order of the years to put 2023 on top, 2023 added
Modified past-articles.html: changed the order of the years to put 2023 on top, 2023 added [Noted issue: this seems to be an unnecessary copy of archived-artciles.html, and no French equivalent exist]
=> 2024 articles changes

learning/esdc-self-paced-web-accessibility-course/module5/figcaption.html, resources/accessible-software-en.html
`<figcaption>` (with a p) is the correct way to write the HTML tag.
Closes #1425
=> Fix typo in figcaption.html
